import { Grid, Page } from '@cd/ui-lib';
import Head from 'next/head';

export default function StoreFront({
    organization
    // products, categories
}) {
    return (
        <Page>
            <Head>
                <title>{organization}</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Grid>Welcome to {organization} storefront</Grid>
        </Page>
    );
}

export async function getServerSideProps({ req }) {
    // const subDomain = await prisma.subDomain.findUnique({
    //     where: {
    //         id: req.headers.host
    //     },
    //     include: {
    //         organization: {
    //             include: {
    //                 address: true,
    //                 products: true,
    //                 images: true,
    //                 siteSetting: true,
    //                 categoryList: true
    //             }
    //         }
    //     }
    // });

    // if (!subDomain) {
    //     return {
    //         props: {
    //             error: 'The domain was not registered in the app'
    //         }
    //     };
    // }

    // return {
    //     props: {
    //         organization: subDomain.organization,
    //         products: subDomain.organization.products
    //     }
    // };
    return { props: { organization: req.headers.host } };
}
