gatewayProxies:
    gatewayProxy:
        service:
            type: ClusterIP
            extraAnnotations:
                cloud.google.com/neg: '{"exposed_ports": {"80":{"name": "ingressgateway"}}}'
        kind:
            deployment:
                replicas: 2
        antiAffinity: true
settings:
    replaceInvalidRoutes: true
    invalidConfigPolicy:
        invalidRouteResponseBody:
            Gloo Edge has invalid configuration. Administrators
            should run `glooctl check` to find and fix config errors.
        invalidRouteResponseCode: 404
        replaceInvalidRoutes: true
