variables:
  DOCKER_DRIVER: overlay2
  REGISTRY: ${REGISTRY}
  REGISTRY_USERNAME: "grasadmin"
  REGISTRY_PASSWORD: "?-+NiLHaZLy5J3q"
  RULES_CHANGES_PATH: "**/*"

stages:
  - test
  - build
  - deploy

.base-rules:
  rules:
  # if it's master/main, CI should always run the job
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
      when: always
  # disable branch one & delay starting CI until an MR is created
    - if: '$CI_PIPELINE_SOURCE == "push"'
      when: never
  # no CI running for a tag
    - if: $CI_COMMIT_TAG
      when: never
  # start jobs for when there are changes in the path defined
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
      changes:
        - $RULES_CHANGES_PATH
  # allow the job to be triggered manually.
    - when: manual
      allow_failure: true
      
.build:
  image: docker:latest
  stage: build
  when: manual
  before_script:
    - docker info
    - docker login -u ${REGISTRY_USERNAME} -p ${REGISTRY_PASSWORD} ${REGISTRY}
  script:
    # Default branch leaves tag empty (= latest tag)
    # All other branches are tagged with the escaped branch name (commit ref slug)
    # - |
    #   if [[ "$CI_COMMIT_BRANCH" == "$CI_DEFAULT_BRANCH" ]]; then
    #     tag=""
    #     echo "Running on default branch '$CI_DEFAULT_BRANCH': tag = 'latest'"
    #   else
    #     tag=":$CI_COMMIT_REF_SLUG"
    #     echo "Running on branch '$CI_COMMIT_BRANCH': tag = $tag"
    #   fi
    - REGISTRY=${REGISTRY}/ docker buildx bake --progress tty --push -f bake.hcl $BUILD

build:
  extends: .build
  parallel:
    matrix:
      - BUILD: [
          "shop",
          "dashboard",
          "widget",
          "main",
          "location",
          "image",
          "payments",
          "supertokens",
        ]
        REGISTRY: ${REGISTRY}

.shop:
  extends: .base-rules
  variables:
    RULES_CHANGES_PATH: "shop/**/*"

.dashboard:
  extends: .base-rules
  variables:
    RULES_CHANGES_PATH: "dashboard/**/*"

.main:
  extends: .base-rules
  variables:
    RULES_CHANGES_PATH: "main/**/*"

.location:
  extends: .base-rules
  variables:
    RULES_CHANGES_PATH: "location/**/*"

.image:
  extends: .base-rules
  variables:
    RULES_CHANGES_PATH: "image/**/*"

.payments:
  extends: .base-rules
  variables:
    RULES_CHANGES_PATH: "payments/**/*"

.dispatch:
  extends: .base-rules
  variables:
    RULES_CHANGES_PATH: "dispatch/**/*"

.widget:
  extends: .base-rules
  variables:
    RULES_CHANGES_PATH: "widget/**/*"