---
.modules:
  - MODULE:
      - app/shop
      - app/dashboard
      - server/main
      - server/location
      - server/payments
      - server/image

stages:
  - cache
  - build
  - deploy

build:
  extends: .module_build
  parallel:
    matrix: !reference [.modules]
  variables:
    TAG: $CI_MERGE_REQUEST_IID
  rules:
    # MR
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
      changes:
        - node_modules
        - ${MODULE}/**/*

deploy:
  extends: .module_deploy
  parallel:
    matrix: !reference [.modules]
  variables:
    TAG: ${CI_COMMIT_SHORT_SHA}
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
      changes:
        - ${MODULE}/**/*

include:
  - .gitlab/ci/cache.gitlab-ci.yml
  - .gitlab/ci/module.gitlab-ci.yml
