---
.modules:
  - MODULE:
      - app/shop
      - app/dashboard
      - server/main
      - server/location
      # - server/payments
      - server/image

include:
  # - .gitlab/ci/cache.gitlab-ci.yml
  - .gitlab/ci/module.gitlab-ci.yml

stages:
  # - cache
  - build
  - deploy

build:
  extends: .module_build
  parallel:
    matrix: !reference [.modules]
  rules:
    # MR
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
    # Production
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
      # changes:
      #   - node_modules
      #   - ${MODULE}/**/*

deploy:
  extends: .module_deploy
  parallel:
    matrix: !reference [.modules]
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
      # changes:
      #   - ${MODULE}/**/*

