stages:
  - cache
  - lint
  - test

include:
  - ".test-ci.yml"
  - ".lint-ci.yml"
  - ".cache-ci.yml"
  - "shop/.gitlab-ci.yml"
  - "dashboard/.gitlab-ci.yml"
  - "main/.gitlab-ci.yml"
  - "location/.gitlab-ci.yml"
  - "payments/.gitlab-ci.yml"
  - "image/.gitlab-ci.yml"
  # - "dispatch/.gitlab-ci.yml"