# modules list
.modules:
  - MODULE: "shop"
    PATH: "apps/shop"
  - MODULE: "dashboard"
    PATH: "apps/dashboard"
  - MODULE: "widget"
    PATH: "apps/widget"
  - MODULE: "main"
    PATH: "server/main"
  - MODULE: "location"
    PATH: "server/location"
  - MODULE: "image"
    PATH: "server/image"
  - MODULE: "payments"
    PATH: "server/payments"
  - MODULE: "supertokens"
    PATH: "Dockerfile.supertokens"

test-protocols:
  stage: test
  rules:
    - changes:
      - mods/${PATH_NAME}/**/*.py
  script:
    - cd "${CI_PROJECT_DIR}/mods/${PATH_NAME}"
    - ~/task venv
    - ~/task init
    - ~/task test
  parallel:
    matrix: !reference [.mod_list]

deploy-protocols:
  stage: deploy
  rules:
    - changes: