.type-tests:
  stage: test
  before_script:
    - cd $MODULE_PATH
  script:
    # - yarn tsc
    - echo typecheck command
  retry:
    max: 2
    when:
      - runner_system_failure
      - stuck_or_timeout_failure
      
.unit-tests:
  stage: test
  before_script:
    - cd $MODULE_PATH
  script:
    # - yarn test:unit-ci
    - echo unit test command
  retry:
    max: 2
    when:
      - runner_system_failure
      - stuck_or_timeout_failure