version: '3.8'

services:
  shop:
    environment:
      NODE_ENV: development
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/root
    expose:
      - 3000
    ports:
      - 3000:3000
    command: "yarn next dev"

  dashboard:
    environment:
      NODE_ENV: development
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - BUILD_TYPE=app
        - BUILD_CONTEXT=shop
    volumes:
      - ./:/root
    expose:
      - 3000
    ports:
      - 3000:3000
    command: "yarn next dev"
  
  # dashboard:
  #   image: docker.io/grasadmin/dashboard
  #   ports:
  #     - '3001:3001'
  #   environment:
  #     - 'NODE_ENV=development'
  #   env_file:
  #     - .env.development

  # help:
  #   image: docker.io/grasadmin/help
  #   ports:
  #     - '3005:3005'
  #   environment:
  #     - 'NODE_ENV=development'
  #   env_file:
  #     - .env.development

  # blog:
  #   image: docker.io/grasadmin/blog
  #   ports:
  #     - '3007:3007'
  #   environment:
  #     - 'NODE_ENV=development'
  #   env_file:
  #     - .env.development

  main:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '6001:6001'
    environment:
      - 'NODE_ENV=development'
    env_file:
      - .env.development

  # location:
  #   image: docker.io/grasadmin/location
  #   ports:
  #     - '6011:6011'
  #   environment:
  #     - 'NODE_ENV=development'
  #   env_file:
  #     - .env.development

  # payments:
  #   image: docker.io/grasadmin/payments
  #   ports:
  #     - '6021:6021'
  #   environment:
  #     - 'NODE_ENV=development'
  #   env_file:
  #     - .env.development

  # image:
  #   image: docker.io/grasadmin/image
  #   ports:
  #     - '6031:6031'
  #   environment:
  #     - 'NODE_ENV=development'
  #   env_file:
  #     - .env.development

  # # dispatch:
  # #   image: docker.io/grasadmin/dispatch
  # #   ports:
  # #     - "6041:6041"
  # # environment:
  # #  - 'NODE_ENV=development'

  # supertokens:
  #   image: docker.io/grasadmin/supertokens:3.14
  #   ports:
  #     - '3567:3567'
  #   env_file:
  #     - .env.development
