FROM node:16

WORKDIR /root
COPY . .

ENV NODE_ENV=production
ENV YARN_VERSION "3.3.1"
ARG BUILD_CONTEXT=$BUILD_CONTEXT

RUN yarn set version $YARN_VERSION
RUN yarn plugin import workspace-tools
RUN yarn workspaces focus @cd/server-$BUILD_CONTEXT
# RUN yarn workspaces focus @cd/server-main && yarn cache clear

RUN yarn server:build $BUILD_CONTEXT

WORKDIR /root/server/$BUILD_CONTEXT

EXPOSE 6001

CMD [ "yarn", "start", "--env", "production" ]