FROM --platform=linux/amd64 registry.supertokens.io/supertokens/supertokens-postgresql:3.14

# ENV POSTGRESQL_USER=postgres
# ENV POSTGRESQL_HOST=db.ahxytltcuydeyhunpahd.supabase.co
# ENV POSTGRESQL_PORT=5432
# ENV POSTGRESQL_DATABASE_NAME=postgres
# ENV POSTGRESQL_CONNECTION_URI="postgresql://postgres:RRJV@y_CK-jz9rj@db.ahxytltcuydeyhunpahd.supabase.co:5432/postgres"

EXPOSE 3567
CMD ["supertokens", "start"]