version: '3.8'

# docker compose files are broken
services:
  app-base:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=development
    volumes:
      - ./:/root
      - monorepo-node-modules:/root/node_modules