# Render.com services blueprint
# define services for each directory in server directory

previewsEnabled: true
previewsExpireAfterDays: 1
services:
- name: main
  type: web
  runtime: docker
  plan: free
  dockerfilePath: ./Dockerfile.server
  dockerContext: .
  registryCredential:
    fromRegistryCreds:
      name: docker
  scaling:
    minInstances: 1         # Required
    maxInstances: 2         # Required
    targetMemoryPercent: 60 # Optional if targetCPUPercent is set (valid: 1-90)
    targetCPUPercent: 60 
  buildFilter:
    paths: # Only trigger a build with changes to these files
      - server/main
      - packages/core-lib
      - packages/data-access
      - packages/eslint-config
    ignoredPaths: # Ignore these files, even if they match a path in 'paths'
      - server/main/test/**
      - packages/core-lib/src/test/**
      - packages/data-access/src/test/**
  region: ohio
  branch: production
  # domains: 
  #   - backend.grascannabis.org
  healthCheckPath: /api/v1/healthcheck
  envVars:
    - key: BUILD_TYPE
      value: server
    - key: BUILD_CONTEXT
      value: main
    - key: PORT
      value: 6001
    - fromGroup: gras-env