/* eslint-disable sonarjs/no-duplicate-string */
import {
	type DailyDealCreateWithSkus,
	type ProductVariant,
	type OrderWithFullDetails,
	type OrganizationWithDashboardDetails,
	type ProductWithDashboardDetails,
	type UserDispensaryStaff,
	type UserWithProfilePicture,
	type DailyDeal,
} from '@cd/data-access';
import { createId } from '@paralleldrive/cuid2';
import { calculateDeliveryDeadline } from './utils/time.util';

const userDispensaryStaff: UserDispensaryStaff = {
	id: 'bf346k4u7xq030hr6wvgiwao',
	firstName: 'Doug',
	lastName: 'Doogie',
	username: 'Doogie123',
	email: 'doug@mcnuggsdispensary.com',
	dialCode: '1',
	phone: '6665555555',
	emailVerified: true,
	isLegalAge: true,
	idVerified: true,
	scannedDOB: new Date(),
	isSignUpComplete: true,
	idFrontImage: null,
	idBackImage: null,
	termsAccepted: true,
	createdAt: new Date(),
	updatedAt: new Date(),
	isSubscribedForWeedText: true,
	profilePicture: {
		userId: 'bf346k4u7xq030hr6wvgiwao',
		id: '1',
		location:
			'https://cdn-cashy-static-assets.lucidchart.com/marketing/blog/2017Q1/7-types-organizational-structure/types-organizational-structures.png',
		// eslint-disable-next-line sonarjs/no-duplicate-string
		blurhash: 'dEHLh[WB2yk8pyoJadR*.7kCMdnjS#M|%1%2Sis.slNH',
		alt: 'Doug Doogie',
		createdAt: new Date(),
		updatedAt: new Date(),
	},
	memberships: [
		{
			role: 'ADMIN',
			organizationId: '2',
			userId: '1',
			createdAt: new Date(),
			updatedAt: new Date(),
		},
	],
};

const notAdminUser: UserWithProfilePicture = {
	id: 'bf346k4u7xq030hr6wvgiwao',
	firstName: 'Sam',
	lastName: 'Samuels',
	username: 'Sammy223',
	email: 'sam@gmail.com',
	phone: '1232343452',
	emailVerified: true,
	isLegalAge: true,
	idVerified: true,
	scannedDOB: new Date(),
	isSignUpComplete: true,
	dialCode: '1',
	idFrontImage: null,
	idBackImage: null,
	termsAccepted: true,
	createdAt: new Date(),
	updatedAt: new Date(),
	isSubscribedForWeedText: true,
	profilePicture: {
		id: '2',
		alt: 'Sam Samuels',
		location:
			'https://www.baltimoremagazine.com/wp-content/uploads/2019/12/baltimore-oriole-s52-11-018-l-0.jpg',
		blurhash: 'dEHLh[WB2yk8pyoJadR*.7kCMdnjS#M|%1%2Sis.slNH',
		createdAt: new Date(),
		updatedAt: new Date(),
	},
};

// @ts-ignore
const organization: OrganizationWithDashboardDetails = {
	id: '1234',
	name: 'McNuggs',
	stripeAccountId: 'acct_1JX2Zz2eZvKYlo2C',
	stripeOnboardingComplete: true,
	dialCode: '1',
	phone: '2475895745',
	termsAccepted: true,
	addressId: '1234',
	address: {
		id: '1234',
		createdAt: new Date(),
		updatedAt: new Date(),
		street1: '2667 Solomons Island Rd',
		street2: '',
		city: 'Annapolis',
		state: 'MD',
		zipcode: 21037,
		country: 'United_States',
		countryCode: 'US',
		coordinateId: '12345678',
		coordinates: {
			id: '12345678',
			radius: 10000,
			latitude: 39.2904,
			longitude: -76.6122,
			createdAt: new Date(),
			updatedAt: new Date(),
		},
	},
	images: [
		{
			id: '1',
			organizationId: '1234',
			createdAt: new Date(),
			updatedAt: new Date(),
			alt: 'McNuggs',
			location:
				'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSxzNuI7e1ZEcBvNPke7da5pcvomN-21e2-zERnn0Z6p2ed4AvkOFXPoSEqtIK1V6tl8wY&usqp=CAU',
			blurhash: '',
		},
	],
	schedule: [
		{
			id: createId(),
			days: 1234560,
			day: 'Monday',
			organizationId: '1234',
			openAt: 9,
			closeAt: 24,
			createdAt: new Date(),
			updatedAt: new Date(),
		},
		{
			id: createId(),
			days: 1234560,
			day: 'Tuesday',
			organizationId: '1234',
			openAt: 9,
			closeAt: 24,
			createdAt: new Date(),
			updatedAt: new Date(),
		},
		{
			id: createId(),
			days: 1234560,
			day: 'Wednesday',
			organizationId: '1234',
			openAt: 9,
			closeAt: 24,
			createdAt: new Date(),
			updatedAt: new Date(),
		},
		{
			id: createId(),
			days: 1234560,
			day: 'Thursday',
			organizationId: '1234',
			openAt: 9,
			closeAt: 24,
			createdAt: new Date(),
			updatedAt: new Date(),
		},
		{
			id: createId(),
			days: 1234560,
			day: 'Monday',
			organizationId: '1234',
			openAt: 9,
			closeAt: 24,
			createdAt: new Date(),
			updatedAt: new Date(),
		},
		{
			id: createId(),
			days: 1234560,
			day: 'Friday',
			organizationId: '1234',
			openAt: 9,
			closeAt: 24,
			createdAt: new Date(),
			updatedAt: new Date(),
		},
		{
			id: createId(),
			days: 1234560,
			day: 'Saturday',
			organizationId: '1234',
			openAt: 9,
			closeAt: 24,
			createdAt: new Date(),
			updatedAt: new Date(),
		},
		{
			id: createId(),
			days: 1234560,
			day: 'Sunday',
			organizationId: '1234',
			openAt: 9,
			closeAt: 24,
			createdAt: new Date(),
			updatedAt: new Date(),
		},
	],
	subdomainId: 'mcnuggs',
	subdomain: {
		id: 'mcnuggs',
		isValid: true,
		createdAt: new Date(),
		updatedAt: new Date(),
	},
	vendorName: 'McNuggs',
	vendorId: '4',
	vendor: {
		id: '4',
		name: 'McNuggs',
		publicName: 'McNuggs',
		createdAt: new Date(),
		updatedAt: new Date(),
	},
	createdAt: new Date(),
	updatedAt: new Date(),
};

const products: ProductWithDashboardDetails[] = [
	{
		id: '1',
		name: 'King OG',
		description: 'turpentines all day baby',
		features: 'fresh, without formaline',
		tags: 'mini, flower, og',
		organizationId: '2',
		rating: 4.5,
		createdAt: new Date(),
		updatedAt: new Date(),
		variants: [
			{
				id: '1',
				name: 'King OG',
				unit: 'g',
				size: 3.5,
				currency: 'USD',
				basePrice: 6999,
				discount: 10,
				stock: 5,
				productId: '1',
				organizationId: '2',
				organizationName: 'Curaleaf',
				quantity: 3,
				rating: 4.5,
				isDiscount: true,
				salePrice: 6499,
				sku: '1234567',
				createdAt: new Date(),
				updatedAt: new Date(),
			},
			{
				id: '2',
				name: 'King OG',
				unit: 'g',
				size: 9,
				currency: 'USD',
				basePrice: 17999,
				discount: 5,
				stock: 9,
				productId: '1',
				organizationId: '2',
				organizationName: 'Curaleaf',
				quantity: 3,
				rating: 4.5,
				isDiscount: true,
				salePrice: 6499,
				sku: '1234567',
				createdAt: new Date(),
				updatedAt: new Date(),
			},
		],
		categories: [
			{
				id: '9',
				name: 'Flower',
				slug: 'flower',
				icon: 'Breakfast',
				createdAt: new Date(),
				updatedAt: new Date(),
			},
		],
		reviews: [
			{
				id: '1',
				rating: 5,
				comment: 'Great thing!',
				productId: '1',
				userId: 'bf346k4u7xq030hr6wvgiwao',
				createdAt: new Date(),
				updatedAt: new Date(),
				user: {
					id: 'bf346k4u7xq030hr6wvgiwao',
					username: 'Sammy223',
					profilePicture: {
						id: '2',
						userId: 'bf346k4u7xq030hr6wvgiwao',
						alt: 'Sam Samuels',
						location:
							'https://www.baltimoremagazine.com/wp-content/uploads/2019/12/baltimore-oriole-s52-11-018-l-0.jpg',
						blurhash: 'dEHLh[WB2yk8pyoJadR*.7kCMdnjS#M|%1%2Sis.slNH',
						createdAt: new Date(),
						updatedAt: new Date(),
					},
				},
			},
		],
	},
	{
		id: '2',
		// eslint-disable-next-line sonarjs/no-duplicate-string
		name: 'Blackberry Kush',
		description: 'Satisfying Liquid Goochy',
		features: 'fresh, relaxing',
		tags: 'flower, og',
		organizationId: '2',
		rating: 4.5,
		createdAt: new Date(),
		updatedAt: new Date(),
		variants: [
			{
				id: '3',
				name: 'Blackberry Kush',
				unit: 'g',
				size: 3.5,
				currency: 'USD',
				basePrice: 6999,
				discount: 5,
				stock: 5,
				productId: '2',
				organizationId: '2',
				organizationName: 'Curaleaf',
				quantity: 3,
				rating: 4.5,
				isDiscount: true,
				salePrice: 6499,
				sku: '1234567',
				createdAt: new Date(),
				updatedAt: new Date(),
			},
			{
				id: '4',
				name: 'Blackberry Nuggs',
				unit: 'g',
				size: 3.5,
				currency: 'USD',
				basePrice: 6999,
				discount: 5,
				stock: 5,
				productId: '3',
				organizationId: '2',
				organizationName: 'Curaleaf',
				quantity: 3,
				rating: 4.5,
				isDiscount: true,
				salePrice: 6499,
				sku: '1234567',
				createdAt: new Date(),
				updatedAt: new Date(),
			},
		],
		categories: [
			{
				id: '9',
				name: 'Flower',
				slug: 'flower',
				icon: 'Breakfast',
				createdAt: new Date(),
				updatedAt: new Date(),
			},
		],
		reviews: [],
	},
];

const variants: ProductVariant[] = [
	{
		id: '1',
		name: 'King OG',
		unit: 'g',
		size: 3.5,
		currency: 'USD',
		basePrice: 6999,
		discount: 10,
		stock: 5,
		productId: '1',
		organizationId: 'bf346k4u7x2b2hhr6wsofppp',
		rating: 4.5,
		organizationName: 'Golden Nugget Dispensary',
		quantity: 3,
		isDiscount: true,
		salePrice: 6499,
		sku: '123',
		createdAt: new Date(),
		updatedAt: new Date(),
	},
	{
		id: '2',
		name: 'King OG',
		unit: 'g',
		size: 9,
		currency: 'USD',
		basePrice: 17999,
		discount: 5,
		rating: 4.5,
		stock: 9,
		productId: '1',
		organizationId: 'bf346k4u7x2b2hhr6wsofppp',
		organizationName: 'Golden Nugget Dispensary',
		quantity: 3,
		isDiscount: true,
		salePrice: 6499,
		sku: '234',
		createdAt: new Date(),
		updatedAt: new Date(),
	},
	{
		id: '3',
		name: 'Blackberry Kush',
		unit: 'g',
		size: 3.5,
		currency: 'USD',
		basePrice: 6999,
		discount: 5,
		stock: 5,
		productId: '2',
		organizationId: 'bf346k4u7x2b2hhr6wvgippp',
		rating: 4.5,
		organizationName: 'Curaleaf MD Reisterstown',
		quantity: 3,
		isDiscount: true,
		salePrice: 6499,
		sku: '1234567',
		createdAt: new Date(),
		updatedAt: new Date(),
	},
	{
		id: '4',
		name: 'Blackberry Nuggs',
		unit: 'g',
		size: 3.5,
		currency: 'USD',
		basePrice: 6999,
		discount: 5,
		stock: 5,
		productId: '3',
		organizationId: 'bf346k4u7x2b2hhr6wvgippp',
		organizationName: 'Curaleaf MD Reisterstown',
		quantity: 3,
		isDiscount: true,
		rating: 4.5,
		salePrice: 6499,
		sku: '1234567',
		createdAt: new Date(),
		updatedAt: new Date(),
	},
];

const orders: OrderWithFullDetails[] = [
	{
		id: '1',
		type: 'delivery',
		subtotal: 12000,
		total: 12399,
		taxFactor: 0.6,
		taxAmount: 1239,
		orderStatus: 'Pending',
		deliveryFee: 12345,
		mileageFee: 2345,
		platformFee: 2356,
		distance: 16466,
		customerId: '1',
		addressId: '5',
		driverId: '2',
		organizationId: '2',
		purchaseId: '1',
		routeId: null,
		isDeliveredOrder: false,
		isCustomerReceivedOrder: false,
		isCompleted: false,
		createdAt: new Date(),
		updatedAt: new Date(),
		deliveryDeadline: calculateDeliveryDeadline(),
		deliveredAt: new Date(),
		isDriverAssigned: false,
		driverAssignedAt: new Date(),
		isProductPickedUp: false,
		productPickedUpAt: new Date(),
		customerReceivedOrderAt: new Date(),
		completedAt: new Date(),
		duration: 262626,
		isDeliveredOnTime: true,
		isWeedTextOrder: true,
		items: [
			{
				id: '3',
				name: 'Blackberry Kush',
				unit: 'g',
				size: 3.5,
				currency: 'USD',
				basePrice: 6999,
				discount: 5,
				stock: 5,
				productId: '2',
				organizationId: '2',
				organizationName: 'Curaleaf',
				quantity: 3,
				rating: 4.5,
				isDiscount: true,
				salePrice: 6499,
				sku: '1234567',
				createdAt: new Date(),
				updatedAt: new Date(),
			},
			{
				id: '4',
				name: 'Blackberry Nuggs',
				unit: 'g',
				size: 3.5,
				currency: 'USD',
				basePrice: 6999,
				discount: 5,
				stock: 5,
				productId: '3',
				organizationId: '2',
				organizationName: 'Curaleaf',
				quantity: 3,
				rating: 4.5,
				isDiscount: true,
				salePrice: 6499,
				sku: '1234567',
				createdAt: new Date(),
				updatedAt: new Date(),
			},
		],
		customer: {
			id: 'bf346k4u7xq030hr6wvgiwao',
			firstName: 'Sam',
			lastName: 'Samuels',
			username: 'Sammy223',
			email: 'sam@gmail.com',
			phone: '1232343452',
			emailVerified: true,
			isLegalAge: true,
			idVerified: true,
			scannedDOB: new Date(),
			isSignUpComplete: true,
			dialCode: '1',
			idFrontImage: null,
			idBackImage: null,
			termsAccepted: true,
			createdAt: new Date(),
			updatedAt: new Date(),
			isSubscribedForWeedText: true,
			profilePicture: {
				location: '',
				id: '1',
				blurhash: '',
				alt: 'Sam Samuels',
				createdAt: new Date(),
				updatedAt: new Date(),
				userId: 'bf346k4u7x2b2hhr6wvgiwao',
			},
			address: [
				{
					id: '12345',
					street1: '123 Harbor St',
					street2: 'Suite 200',
					city: 'Baltimore',
					state: 'MD',
					zipcode: 21230,
					country: 'United_States',
					countryCode: 'US',
					coordinateId: '1',
					createdAt: new Date(),
					updatedAt: new Date(),
					coordinates: {
						id: '1',
						latitude: 33,
						longitude: 81,
						radius: 1000000,
						createdAt: new Date(),
						updatedAt: new Date(),
					},
				},
			],
		},
		driver: {
			id: 'bf346k4u7x2b2hhr6wvgiwao',
			email: 'bmejiadeveloper2@gmail.com',
			createdAt: new Date(),
			updatedAt: new Date(),
			licenseNumber: '123456789',
			user: {
				id: 'bf346k4u7x2b2hhr6wvgiwao',
				firstName: 'Bryant',
				lastName: 'Mejia',
				username: 'BigChiefa',
				email: 'bmejiadeveloper2@gmail.com',
				phone: '1232343456',
				emailVerified: false,
				isLegalAge: null,
				idVerified: false,
				isSignUpComplete: false,
				dialCode: '1',
				idFrontImage: '',
				idBackImage: '',
				termsAccepted: false,
				scannedDOB: new Date(),
				createdAt: new Date(),
				updatedAt: new Date(),
				isSubscribedForWeedText: false,
				profilePicture: {
					location: '',
					id: '1',
					blurhash: '',
					alt: 'Bryant Mejia',
					createdAt: new Date(),
					updatedAt: new Date(),
					userId: 'bf346k4u7x2b2hhr6wvgiwao',
				},
				address: [
					{
						id: '12345',
						street1: '123 Harbor St',
						street2: 'Suite 200',
						city: 'Baltimore',
						state: 'MD',
						zipcode: 21230,
						country: 'United_States',
						countryCode: 'US',
						coordinateId: '1',
						createdAt: new Date(),
						updatedAt: new Date(),
						coordinates: {
							id: '1',
							latitude: 33,
							longitude: 81,
							radius: 1000000,
							createdAt: new Date(),
							updatedAt: new Date(),
						},
					},
				],
			},
		},
		route: [
			{ latitude: 33, longitude: 81 },
			{ latitude: 34, longitude: 81 },
			{ latitude: 35, longitude: 81 },
			{ latitude: 36, longitude: 81 },
			{ latitude: 37, longitude: 81 },
			{ latitude: 38, longitude: 81 },
			{ latitude: 39, longitude: 81 },
			{ latitude: 40, longitude: 82 },
		],
		destinationAddress: {
			id: '1',
			street1: '123 King St',
			street2: 'Suite 200',
			city: 'Lancaster',
			state: 'PA',
			zipcode: 17602,
			country: 'United_States',
			countryCode: 'US',
			coordinateId: '1',
			createdAt: new Date(),
			updatedAt: new Date(),
			coordinates: {
				id: '1',
				latitude: 33,
				longitude: 81,
				radius: 1000000,
				createdAt: new Date(),
				updatedAt: new Date(),
			},
		},
		purchase: {
			id: '2',
			paymentStatus: 'Paid',
			gateway: 'stripe',
			type: 'card',
			amount: 23444,
			token: '12345',
			orderId: '2',
			createdAt: new Date(),
			updatedAt: new Date(),
		},
		organization,
	},
];

const dailyDealsCreate: DailyDealCreateWithSkus[] = [
	{
		title: 'Fire deals happening now',
		description:
			"Warm up with these FIRE DEALS!! We're selling out fast! Get yours now!!",
		startTime: new Date(),
		// end time is 24 hours from now
		endTime: new Date(Date.now() + 24 * 60 * 60 * 1000),
		organizationId: 'bf346k4u7x2b2hhr6wsofppp',
		organization,
		products: variants.map(
			({ sku, quantity, isDiscount, discount, organizationId }) => ({
				sku,
				quantity,
				isDiscount,
				discount,
				organizationId,
			}),
		),
	},
];

const dailyDeals: DailyDeal[] = [
	{
		id: '1',
		title: 'You dont want to miss this!',
		description: "You dont want to miss this! Order before we're sold out!",
		isExpired: false,
		organizationId: 'bf346k4u7x2b2hhr6wsofppp',
		startTime: new Date(),
		// set date for tomorrow
		endTime: new Date(new Date().getTime() + 24 * 60 * 60 * 1000),
		// products: [
		// 	{
		// 		name: 'Product 1',
		// 		id: '1',
		// 		sku: 1234567,
		// 		organizationId: '1234',
		// 		organizationName: 'Golden Nugget Dispensary',
		// 		productId: '123',
		// 		rating: 4.3,
		// 		unit: 'g',
		// 		size: 7,
		// 		quantity: 1,
		// 		basePrice: 3599,
		// 		discount: 3,
		// 		isDiscount: true,
		// 		salePrice: 3499,
		// 		currency: 'USD',
		// 		stock: 100,
		// 		createdAt: new Date(),
		// 		updatedAt: new Date(),
		// 	},
		// ],
		total: 19799,
	},
];

export {
	userDispensaryStaff,
	notAdminUser,
	organization,
	products,
	orders,
	variants,
	dailyDealsCreate,
	dailyDeals,
};
