import { format } from 'date-fns-tz';
import { defineField, defineType } from 'sanity';
import { AutoPreviewPane } from '../components';
import author from './author';

export default defineType({
	name: 'post',
	title: 'Post',
	type: 'document',
	fields: [
		defineField({
			name: 'title',
			title: 'Title',
			type: 'string',
			validation: (rule) => rule.required(),
		}),
		defineField({
			name: 'slug',
			title: 'Slug',
			type: 'slug',
			options: {
				source: 'title',
				maxLength: 96,
				isUnique: (value, context) => context.defaultIsUnique(value, context),
			},
			validation: (Rule) => Rule.required(),
		}),
		defineField({
			name: 'excerpt',
			title: 'Excerpt',
			type: 'text',
			rows: 4,
		}),
		defineField({
			name: 'mainImage',
			title: 'Main image',
			type: 'image',
			options: {
				hotspot: true,
			},
		}),
		defineField({
			name: 'body',
			title: 'Body',
			type: 'blockContent',
		}),
		defineField({
			name: 'date',
			title: 'Date',
			type: 'datetime',
			initialValue: () => new Date().toISOString(),
		}),
		defineField({
			name: 'author',
			title: 'Author',
			type: 'reference',
			to: [{ type: author.name }],
		}),
		defineField({
			name: 'shareImage',
			title: 'Social Media Image',
			description:
				"A social media image generated by Next.js. It can't modified.",
			type: 'image',
			readOnly: true,
		}),
		defineField({
			name: 'categories',
			title: 'Categories',
			type: 'array',
			of: [{ type: 'reference', to: { type: 'category' } }],
		}),
		defineField({
			type: 'string',
			name: 'hiddenPreviewField',
			components: {
				field: AutoPreviewPane,
			},
		}),
	],
	preview: {
		select: {
			title: 'title',
			author: 'author.name',
			date: 'date',
			media: 'mainImage',
		},
		prepare({ title, media, author, date }) {
			const subtitles = [
				author && `by ${author}`,
				date && `on ${format(date, 'LLL d, yyyy')}`,
			].filter(Boolean);

			return { title, media, subtitle: subtitles.join(' ') };
		},
	},
});
