import { defineField, defineType } from 'sanity';
import { AutoPreviewPane } from '../components';

export default defineType({
	name: 'post',
	title: 'Post',
	type: 'document',
	fields: [
		defineField({
			name: 'title',
			title: 'Title',
			type: 'string',
		}),
		defineField({
			name: 'slug',
			title: 'Slug',
			type: 'slug',
			validation: (Rule) => Rule.required(),
			options: {
				source: 'title',
				maxLength: 96,
			},
		}),
		defineField({
			name: 'excerpt',
			title: 'Excerpt',
			type: 'text',
			rows: 4,
		}),
		defineField({
			name: 'mainImage',
			title: 'Main image',
			type: 'image',
			options: {
				hotspot: true,
			},
		}),
		defineField({
			name: 'body',
			title: 'Body',
			type: 'blockContent',
		}),
		defineField({
			name: 'shareImage',
			title: 'Social Media Image',
			description:
				"A social media image generated by Next.js. It can't modified.",
			type: 'image',
			readOnly: true,
		}),
		defineField({
			name: 'categories',
			title: 'Categories',
			type: 'array',
			of: [{ type: 'reference', to: { type: 'category' } }],
		}),
		defineField({
			type: 'string',
			name: 'hiddenPreviewField',
			components: {
				field: AutoPreviewPane,
			},
		}),
	],
	// preview: {
	// 	select: {
	// 		title: 'title',
	// 		author: 'author.name',
	// 		media: 'mainImage',
	// 	},
	// 	prepare(selection) {
	// 		const { author } = selection;
	// 		return { ...selection, subtitle: author && `by ${author}` };
	// 	},
	// },
});
