import { defineConfig } from 'tsup';

export default defineConfig((options) => ({
	entry: {
		index: 'src/index.ts',
		components: 'src/components/index.ts',
		hooks: 'src/hooks/index.ts',
	},
	splitting: true,
	treeshake: true,
	clean: true,
	format: ['esm'],
	platform: 'browser',
	target: ['es2020', 'chrome70', 'edge18', 'firefox70', 'node18'],
	tsconfig: new URL('./tsconfig.build.json', import.meta.url).pathname,
	sourcemap: !options.watch,
	minify: !options.watch,
	external: [
		'@gras/core',
		'@gras/data-access',
		'@paralleldrive/cuid2',
		'path',
		'crypto',
		'fs',
		'zlib',
		'stream',
		'swr',
		'twilio',
		'mongodb',
		'mongodb-client-encryption',
		'kerberos',
		'@mongodb-js/zstd',
		'snappy',
		'aws4',
		'@mongodb-js/zstd-darwin-arm64',
		'@napi-rs',
		'react-google-recaptcha',
		'next-auth/react',
		'cookies-next'
	],
}));
