---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-shop
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
  - host: "grascannabis.org"
    http:
      paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: gras-service-shop
              port:
                number: 80
  - host: "www.grascannabis.org"
    http:
      paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: gras-service-shop
              port:
                number: 80
  - host: "*.grascannabis.org"
    http: 
      paths: 
        - path: /_stores
          pathType: Prefix
          backend:
            service:
              name: gras-service-shop
              port:
                number: 80