---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-shop
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
    - host: hello.grascannabis.org
      http:
        paths:
        - pathType: Prefix
          path: "/"
          backend:
            service:
              name: gras-service-hello
              port:
                number: 80
    # - host: app.grascannabis.org
    #   http:
    #     paths:
    #     - pathType: Prefix
    #       path: "/"
    #       backend:
    #         service:
    #           name: gras-service-admin
    #           port:
    #             number: 80
    - http:
        paths:
        - pathType: Prefix
          path: "/"
          backend:
            service:
              name: gras-service-shop
              port:
                number: 80