---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-all-egress
spec:
  podSelector: 
    matchLabels:
      gras-server-main: gras-server-main
      gras-server-dispatch: gras-server-dispatch
  egress:
  - {}
  policyTypes:
  - Egress
