apiVersion: gateway.solo.io/v1
kind: RouteTable
metadata:
  name: gras-backend-server-routes
  namespace: gloo-system
  labels:
    domain: 'backend.grascannabis.org'
spec:
  routes:
    - matchers:
        - prefix: /main
      options:
        regexRewrite:
          pattern:
            regex: ^/main(/.*)$
          substitution: \1
      routeAction:
        single:
          upstream:
            name: default-gras-server-main-8080
            namespace: gloo-system
    - matchers:
        - prefix: /image
      options:
        regexRewrite:
          pattern:
            regex: ^/image(/.*)$
          substitution: \1
      routeAction:
        single:
          upstream:
            name: default-gras-server-image-8080
            namespace: gloo-system
    - matchers:
        - prefix: /payments
      options:
        regexRewrite:
          pattern:
            regex: ^/payments(/.*)$
          substitution: \1
      routeAction:
        single:
          upstream:
            name: default-gras-server-payments-8080
            namespace: gloo-system