apiVersion: gateway.solo.io/v1
kind: RouteTable
metadata:
  name: gras-backend-server-routes
  namespace: gloo-system
  labels:
    domain: 'backend.grascannabis.org'
spec:
  routes:
    - matchers:
        - prefix: /main
      inheritablePathMatchers: true
      routeAction:
        single:
          upstream:
            name: default-gras-server-main-8080
            namespace: gloo-system
