---
apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: default
type: Opaque
stringData:
  # POSTGRESQL_CONNECTION_URI: 'postgresql://postgres:RRJV@y_CK-jz9rj@db.ahxytltcuydeyhunpahd.supabase.co:5432/postgres'
  POSTGRESQL_DATABASE_NAME: 'postgres'
  POSTGRESQL_PORT: '5432'
  POSTGRESQL_HOST: 'db.ahxytltcuydeyhunpahd.supabase.co'
  POSTGRESQL_USER: 'postgres'
  POSTGRESQL_PASSWORD: 'RRJV@y_CK-jz9rj'
