---
apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: default
type: Opaque
stringData:
  # POSTGRESQL_CONNECTION_URI: 'postgresql://postgres:TdRI1pIMnTkBHKRq@db.apcnayhzxaforyeoqdjq.supabase.co:5432/postgres'
  POSTGRESQL_DATABASE_NAME: 'postgres'
  POSTGRESQL_PORT: '5432'
  POSTGRESQL_HOST: 'db.apcnayhzxaforyeoqdjq.supabase.co'
  POSTGRESQL_USER: 'postgres'
  POSTGRESQL_PASSWORD: 'TdRI1pIMnTkBHKRq'
