---
apiVersion: v1
kind: Service
metadata:
  name: supertokens
  labels:
    app.kubernetes.io/version: 3.12.0
    app.kubernetes.io/managed-by: supertokens
spec:
  type: ClusterIP
  ports:
    - port: 3567
      targetPort: 3567
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: supertokens
    app.kubernetes.io/instance: supertokens
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: supertokens
  labels:
    app.kubernetes.io/version: 3.12.0
    app.kubernetes.io/managed-by: supertokens
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: supertokens
      app.kubernetes.io/instance: supertokens
  template:
    metadata:
      annotations:
        config.linkerd.io/enable-external-profiles: 'true'
      labels:
        app.kubernetes.io/name: supertokens
        app.kubernetes.io/instance: supertokens
    spec:
      imagePullSecrets: []
      serviceAccountName: default
      securityContext:
        {}
        # fsGroup: 2000
      volumes:
        - name: gras-tls-secret
          secret:
            secretName: gras-cannabis-org
      containers:
        - name: supertokens
          securityContext:
            {}
            # capabilities:
            #   drop:
            #   - ALL
            # readOnlyRootFilesystem: true
            # runAsNonRoot: true
            # runAsUser: 1000
          image: grasadmin/supertokens-mysql:1.0
          imagePullPolicy: Always
          volumeMounts:
            - name: gras-tls-secret
              mountPath: '/mnt/tls.crt'
              subPath: tls.crt
          env:
            - name: 'MYSQL_CONNECTION_URI'
              # value: "mysql://hjl13pett5q5hdb0b6vs:pscale_pw_Dl9qggUnN02NIVAWDXa19Rsrcv8yCELmjNw1jSaMdb3@aws.connect.psdb.cloud:3306/cannabis_delivery_v1?ssl={\"rejectUnauthorized\":true}"
              value: 'mysql://hjl13pett5q5hdb0b6vs:pscale_pw_Dl9qggUnN02NIVAWDXa19Rsrcv8yCELmjNw1jSaMdb3@aws.connect.psdb.cloud:3306/cannabis_delivery_v1?sslaccept=strict&sslcert=/mnt/tls.cert'
            - name: 'SUPERTOKENS_PORT'
              value: '3567'
            - name: 'MYSQL_CONNECTION_POOL_SIZE'
              value: '5'
            - name: 'ACCESS_TOKEN_VALIDITY'
              value: '3600'
            - name: 'ACCESS_TOKEN_BLACKLISTING'
              value: 'false'
            - name: 'ACCESS_TOKEN_SIGNING_KEY_DYNAMIC'
              value: 'true'
            - name: 'ACCESS_TOKEN_SIGNING_KEY_UPDATE_INTERVAL'
              value: '168'
            - name: 'REFRESH_TOKEN_VALIDITY'
              value: '144000'
            - name: 'PASSWORD_RESET_TOKEN_LIFETIME'
              value: '3600000'
            - name: 'EMAIL_VERIFICATION_TOKEN_LIFETIME'
              value: '86400000'
            - name: 'PASSWORDLESS_MAX_CODE_INPUT_ATTEMPTS'
              value: '5'
            - name: 'PASSWORDLESS_CODE_LIFETIME'
              value: '900000'
            - name: 'BASE_PATH'
              value: ''
            - name: 'DISABLE_TELEMETRY'
              value: 'false'
            - name: 'MAX_SERVER_POOL_SIZE'
              value: '10'
          ports:
            - name: http
              containerPort: 3567
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /hello
              port: http
          readinessProbe:
            httpGet:
              path: /hello
              port: http
          resources:
            # We usually recommend not to specify default resources and to leave this as a conscious
            # choice for the user. This also increases chances charts run on environments with little
            # resources, such as Minikube. If you do want to specify resources, uncomment the following
            # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
            limits:
              cpu: 100m
              memory: 128Mi
            requests:
              cpu: 100m
              memory: 128Mi
      nodeSelector: {}
      # affinity: {}
      # podAntiAffinity:
      #   preferredDuringSchedulingIgnoredDuringExecution:
      #     - weight: 1
      #       podAffinityTerm:
      #         labelSelector:
      #           matchExpressions:
      #             - key: "app.kubernetes.io/name"
      #               operator: In
      #               values:
      #                 - supertokens
      #         topologyKey: kubernetes.io/hostname
      tolerations: []
# ---
# # apply for autoscaling
# apiVersion: autoscaling/v2beta1
# kind: HorizontalPodAutoscaler
# metadata:
#   name: supertokens
#   labels:
#     app.kubernetes.io/version: 3.12.0
#     app.kubernetes.io/managed-by: supertokens
# spec:
#   scaleTargetRef:
#     apiVersion: apps/v1
#     kind: Deployment
#     name: supertokens
#   minReplicas: 1
#   maxReplicas: 1
#   metrics:
#     - type: Resource
#       resource:
#         name: cpu
#         targetAverageUtilization: 80
#     - type: Resource
#       resource:
#         name: memory
#         targetAverageUtilization: 80
# ---
# apiVersion: v1
# kind: ServiceAccount
# metadata:
#   name: supertokens-default
#   labels:
#     app.kubernetes.io/version: 3.12.0
#     app.kubernetes.io/managed-by: supertokens
#   annotations: {}
