---
apiVersion: v1
kind: Service
metadata:
  name: gras-next-service
spec:
  type: ClusterIP
  selector:
    component: gras-next-deployment
  ports:
    - protocol: TCP
      port: 8080
      targetPort: gras-next-port
