---
apiVersion: v1
kind: Service
metadata:
  name: supertokens
  labels:
    app.kubernetes.io/version: 3.14.0
    app.kubernetes.io/managed-by: supertokens
spec:
  type: ClusterIP
  ports:
    - port: 3567
  selector:
    app.kubernetes.io/name: supertokens
    app.kubernetes.io/instance: supertokens
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: supertokens
  labels:
    app.kubernetes.io/version: 3.14.0
    app.kubernetes.io/managed-by: supertokens
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: supertokens
      app.kubernetes.io/instance: supertokens
  replicas: 2
  template:
    metadata:
      labels:
        app.kubernetes.io/name: supertokens
        app.kubernetes.io/instance: supertokens
    spec:
      containers:
        - name: supertokens
          image: grasadmin/supertokens-postgres:3.14
          imagePullPolicy: IfNotPresent

          env:
            # - name: 'SUPERTOKENS_HOST'
            #   value: '0.0.0.0'
            - name: 'SUPERTOKENS_PORT'
              value: '3567'
            - name: 'POSTGRESQL_CONNECTION_POOL_SIZE'
              value: '1'
            - name: 'BASE_PATH'
              value: ''
            - name: 'POSTGRESQL_CONNECTION_URI'
              value: 'postgresql://postgres:RRJV@y_CK-jz9rj@db.ahxytltcuydeyhunpahd.supabase.co:5432/postgres'
            - name: 'POSTGRESQL_DATABASE_NAME'
              value: 'postgres'
            - name: 'POSTGRESQL_PORT'
              value: '5432'
            - name: 'POSTGRESQL_HOST'
              value: 'db.ahxytltcuydeyhunpahd.supabase.co'
            - name: 'POSTGRESQL_USER'
              value: 'postgres'
            - name: 'POSTGRESQL_PASSWORD'
              value: 'RRJV@y_CK-jz9rj'

          # envFrom:
          #   - secretRef:
          #       name: postgres-secret

          ports:
            - containerPort: 3567

          livenessProbe:
            httpGet:
              path: /hello
              port: 3567
            failureThreshold: 2
            initialDelaySeconds: 30
            periodSeconds: 5
            timeoutSeconds: 50

          readinessProbe:
            httpGet:
              path: /hello
              port: 3567
            failureThreshold: 2
            initialDelaySeconds: 30
            periodSeconds: 5
            timeoutSeconds: 50

          resources:
            limits:
              cpu: 100m
              memory: 128Mi
            requests:
              cpu: 100m
              memory: 128Mi

      affinity:
        {}
        # podAntiAffinity:
        #   preferredDuringSchedulingIgnoredDuringExecution:
        #     - weight: 1
        #       podAffinityTerm:
        #         labelSelector:
        #           matchExpressions:
        #             - key: "app.kubernetes.io/name"
        #               operator: In
        #               values:
        #                 - supertokens
        #         topologyKey: kubernetes.io/hostname
# ---
# apiVersion: v1
# kind: ServiceAccount
# metadata:
#   name: supertokens-default
#   labels:
#     app.kubernetes.io/version: 3.14.0
#     app.kubernetes.io/managed-by: supertokens
#   annotations: {}
