---
apiVersion: v1
kind: Service
metadata:
  name: supertokens
  labels:
    app.kubernetes.io/version: "7.0"
    app.kubernetes.io/managed-by: supertokens
spec:
  type: ClusterIP
  ports:
    - port: 3567
      targetPort: 3567
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: supertokens
    app.kubernetes.io/instance: supertokens
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: supertokens
  labels:
    app.kubernetes.io/version: "7.0"
    app.kubernetes.io/managed-by: supertokens
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: supertokens
      app.kubernetes.io/instance: supertokens
  template:
    metadata:
      labels:
        app.kubernetes.io/name: supertokens
        app.kubernetes.io/instance: supertokens
    spec:
      securityContext:
        {}
        # fsGroup: 2000
      containers:
        - name: supertokens
          securityContext:
            {}
            # capabilities:
            #   drop:
            #   - ALL
            # readOnlyRootFilesystem: true
            # runAsNonRoot: true
            # runAsUser: 1000
          image: registry.supertokens.io/supertokens/supertokens-postgresql:7.0
          imagePullPolicy: Always
          env:
            - name: 'SUPERTOKENS_HOST'
              value: '0.0.0.0'
            - name: 'SUPERTOKENS_PORT'
              value: '3567'
            - name: 'POSTGRESQL_CONNECTION_POOL_SIZE'
              value: '5'
            - name: 'BASE_PATH'
              value: ''
            - name: 'POSTGRESQL_CONNECTION_URI'
              value: 'postgresql://postgres:TdRI1pIMnTkBHKRq@db.apcnayhzxaforyeoqdjq.supabase.co:5432/postgres'
            - name: 'POSTGRESQL_DATABASE_NAME'
              value: 'postgres'
            - name: 'POSTGRESQL_PORT'
              value: '5432'
            - name: 'POSTGRESQL_HOST'
              value: 'db.apcnayhzxaforyeoqdjq.supabase.co'
            - name: 'POSTGRESQL_USER'
              value: 'postgres'
            - name: 'POSTGRESQL_PASSWORD'
              value: 'TdRI1pIMnTkBHKRq'
            - name: 'PASSWORDLESS_MAX_CODE_INPUT_ATTEMPTS'
              value: '5'
            - name: 'DISABLE_TELEMETRY'
              value: 'true'

          ports:
            - containerPort: 3567
              protocol: TCP
              name: http

          livenessProbe:
            httpGet:
              path: /hello
              port: http
            failureThreshold: 2
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 50

          readinessProbe:
            httpGet:
              path: /hello
              port: http
            failureThreshold: 2
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 50

          resources:
            limits:
              cpu: 200m
              memory: 256Mi
            requests:
              cpu: 128m
              memory: 175Mi
      affinity:
        {}
          # podAntiAffinity:
          #   preferredDuringSchedulingIgnoredDuringExecution:
          #     - weight: 1
          #       podAffinityTerm:
          #         labelSelector:
          #           matchExpressions:
          #             - key: "app.kubernetes.io/name"
          #               operator: In
          #               values:
          #                 - supertokens
          #         topologyKey: kubernetes.io/hostname
