---
apiVersion: v1
kind: Service
metadata:
  name: redis-cart
  labels:
    service: redis-cart
  namespace: redis
spec:
  selector:
    app: redis-cart
  ports:
    - protocol: TCP
      port: 6301
      targetPort: r-cart-port
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: redis-cart
  namespace: redis
  labels:
    app: redis-cart
spec:
  serviceName: redis-cart
  replicas: 1
  selector:
    matchLabels:
      app: redis-cart
  template:
    metadata:
      labels:
        app: redis-cart
    spec:
      containers:
        - name: redis
          image: redis:6.2.5
          command: ['redis-server']
          args: ['/conf/redis.conf']
          env:
            - name: REDIS_CLUSTER_ANNOUNCE_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
          ports:
            - containerPort: 6301
              name: r-cart-port
            - containerPort: 16301
              name: r-cart-gossip
          volumeMounts:
            - name: data
              mountPath: /data
            - name: redis-config
              mountPath: /conf
          resources:
            requests:
              cpu: '0.5'
              memory: '1Gi'
            limits:
              cpu: '1'
              memory: '2Gi'
      volumes:
        - name: redis-config
          configMap:
            name: redis-configmap
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes: ['ReadWriteOnce']
        resources:
          requests:
            storage: 1Gi
# ---
# apiVersion: autoscaling/v2
# kind: HorizontalPodAutoscaler
# metadata:
#   name: redis-cart-hpa
#   namespace: redis
# spec:
#   scaleTargetRef:
#     apiVersion: apps/v1
#     kind: StatefulSet
#     name: redis-cart
#   minReplicas: 1
#   maxReplicas: 3
#   metrics:
#   - type: Resource
#     resource:
#       name: cpu
#       target:
#         type: Utilization
#         averageUtilization: 50
