apiVersion: gloo.solo.io/v1
kind: Upstream
metadata:
  name: default-gras-server-main-8080
  namespace: gloo-system
spec:
  discoveryMetadata:
    labels:
      service: gras-server-main
  kube:
    selector:
      app: gras-server-main
    serviceName: gras-server-main
    serviceNamespace: default
    servicePort: 8080
  # ----- Health Check (a.k.a. active health checks) -------
  healthChecks:
    - healthyThreshold: 2
      httpHealthCheck:
        path: /api/v1/healthcheck
      interval: 5s
      timeout: 5s
      unhealthyThreshold: 2
      reuseConnection: false
      noTrafficInterval: 5s # Start sending health checks after 5 seconds (default is 60)
  # ----- Outlier Detection  (a.k.a. passive health checks) ------
  outlierDetection:
    consecutive5xx: 3
    maxEjectionPercent: 50
    interval: 5s
  circuitBreakers:
    maxRetries: 10 # Default is 3
  # ----- Help with consistency between the Kubernetes control-plane and the Gloo control-plane ------
  ignoreHealthOnHostRemoval: true
