apiVersion: gloo.solo.io/v1
kind: Upstream
metadata:
  name: gras-shop-8080
  namespace: gloo-system
spec:
  discoveryMetadata:
    labels:
      service: gras-shop
  kube:
    selector:
      app: gras-shop
    serviceName: gras-shop
    serviceNamespace: default
    servicePort: 8080
  # ----- Health Check (a.k.a. active health checks) -------
  healthChecks:
  - healthyThreshold: 1
    httpHealthCheck:
      path: /
    interval: 3s
    timeout: 1s
    unhealthyThreshold: 1
    reuseConnection: false
    noTrafficInterval: 5s # Start sending health checks after 5 seconds (default is 60)
  # ----- Outlier Detection  (a.k.a. passive health checks) ------
  outlierDetection:
    consecutive5xx: 3
    maxEjectionPercent: 50
    interval: 1s
  circuitBreakers:
    maxRetries: 10 # Default is 3
  # ----- Help with consistency between the Kubernetes control-plane and the Gloo control-plane ------
  ignoreHealthOnHostRemoval: true