apiVersion: gloo.solo.io/v1
kind: Upstream
metadata:
  name: default-gras-shop-8080
  namespace: gloo-system
spec:
  discoveryMetadata:
    labels:
      service: gras-shop
  kube:
    selector:
      app: gras-shop
    serviceName: gras-shop
    serviceNamespace: default
    servicePort: 8080
  healthChecks:
    - healthyThreshold: 2
      httpHealthCheck:
        path: /api/healthcheck
      interval: 5s
      timeout: 5s
      unhealthyThreshold: 2
      reuseConnection: false
      noTrafficInterval: 60s
  outlierDetection:
    consecutive5xx: 3
    maxEjectionPercent: 50
    interval: 5s
  circuitBreakers:
    maxRetries: 10
  ignoreHealthOnHostRemoval: true
