---
apiVersion: gateway.solo.io/v1
kind: VirtualService
metadata:
  name: default
  namespace: gloo-system
spec:
  virtualHost:
    domains:
    - '*'
    routes:
    - matchers:
      - prefix: /
      options:
        retries:
          retryOn: 'connect-failure,5xx'
          numRetries: 5
          perTryTimeout: 1s
      delegateAction:
        selector:
          # labels:
          #   domain: grascannabis.org
          expressions:
            - key: domain
              operator: In
              values: 
                - grascannabis.org
                - app.grascannabis.org
                - backend.grascannabis.org
                - widget.grascannabis.org
                - *.grascannabis.org
          namespaces:
          - gloo-system
