import Head from 'next/head';
import Link from 'next/link';
import { Page, H1, H2, H3, H4, H5 } from '@cd/shared-ui';

export default function Dashboard() {
    return (
        <Page>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <H1>
                <Link href="/">Welcome to Gras Cannabis</Link>
            </H1>
            <H2>
                <Link href="/">Welcome to Gras Cannabis</Link>
            </H2>
            <H3>
                <Link href="/">Welcome to Gras Cannabis</Link>
            </H3>
            <H4>
                <Link href="/">Welcome to Gras Cannabis</Link>
            </H4>
            <H5>
                <Link href="/">Welcome to Gras Cannabis</Link>
            </H5>
            <H1>
                <Link href="/">Welcome to Gras Cannabis</Link>
            </H1>
            <H2>
                <Link href="/">Welcome to Gras Cannabis</Link>
            </H2>
            <H3>
                <Link href="/">Welcome to Gras Cannabis</Link>
            </H3>
            <H4>
                <Link href="/">Welcome to Gras Cannabis</Link>
            </H4>
            <H5>
                <Link href="/">Welcome to Gras Cannabis</Link>
            </H5>
            <H1>
                <Link href="/">Welcome to Gras Cannabis</Link>
            </H1>
            <H2>
                <Link href="/">Welcome to Gras Cannabis</Link>
            </H2>
            <H3>
                <Link href="/">Welcome to Gras Cannabis</Link>
            </H3>
            <H4>
                <Link href="/">Welcome to Gras Cannabis</Link>
            </H4>
            <H5>
                <Link href="/">Welcome to Gras Cannabis</Link>
            </H5>
        </Page>
    );
}
