import Head from 'next/head';
import Image from 'next/image';
import Link from 'next/link';
import { Button, Page, H1, H2, H3, H4, H5 } from 'shared-ui';

export default function Dashboard() {
    return (
        <Page>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <H1>
                <Link href="/">Welcome to Gras Cannabis</Link>
            </H1>
            <H2>
                <Link href="/">Welcome to Gras Cannabis</Link>
            </H2>
            <H3>
                <Link href="/">Welcome to Gras Cannabis</Link>
            </H3>
            <H4>
                <Link href="/">Welcome to Gras Cannabis</Link>
            </H4>
        </Page>
    );
}
