import { calcSalePrice } from '@cd/shared-lib';
import { LoadingDots } from '@cd/shared-ui';
import Head from 'next/head';
import Image from 'next/image';
export default function Home() {
    const item = {
        price: 100,
        discount: 5,
        sale: true
    };
    return (
        <div>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <main>
                <h1>
                    Welcome to <a href="https://nextjs.org">Next.js!</a>
                </h1>
                <div>
                    <LoadingDots />
                    <p>Price: {item.price}</p>
                    {item.sale && (
                        <>
                            <p>This item is on sale: {item.discount} % off</p>
                            <p>${calcSalePrice(item.price, item.discount)}</p>
                        </>
                    )}
                </div>
            </main>

            <footer>
                <a
                    href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
                    target="_blank"
                    rel="noopener noreferrer"
                >
                    Powered by{' '}
                    <span>
                        <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
                    </span>
                </a>
            </footer>
        </div>
    );
}
