export type POS = 'dutchie' | 'blaze' | 'weedmaps';
export type Inventory = 'metrc' | 'biotrack';
export interface SiteSetting {
	// theme: string;
	// accentFont: string;
	primaryColor: string;
	secondaryColor: string;
	tertiaryColor: string;
	textColor: string;
	backgroundColor: string;
	showTitle: boolean;
	showBanner: boolean;
	showDescription: boolean;
	title: string;
	description: string;
	bannerText: string;
}
export interface Dispensary {
	id: string;
	name: string;
	slug: string;
	domain?: string;
	billingId?: string;
	subscriptionPlanId?: string;
	address?: unknown;
	dialCode?: string;
	phone?: string;
	schedule?: Schedule[];
	ecommerceUrl?: string;
	timeZone?: string;
	isSubscribedForDelivery?: boolean;
	isSubscribedForPickup?: boolean;
	isSubscribedForMessaging?: boolean;
	termsAccepted?: boolean;
	billingProvider?: string;
	stripeAccountId?: string;
	stripeOnboardingComplete?: boolean;
	siteSetting?: SiteSetting;
	images?: { location: string; blurhash: string; alt: string }[];
	pos?: POS;
	isSignupComplete?: boolean;

	weedTextPhoneNumber?: string;
	weedTextSegmentId?: string;

	members?: string[];
	createdAt?: Date;
	updatedAt?: Date;
	showInMarketPlace?: boolean;
	orders?: unknown[];
}

//  export type Dispensary = Prisma.OrganizationUncheckedCreateInput & {
// 	address: AddressPayload;
// 	schedule: Prisma.ScheduleCreateManyOrganizationInput;
// 	images: Prisma.ImageOrganizationCreateManyOrganizationInput[];
// 	products: Prisma.ProductCreateInput[];
// 	categoryList: Prisma.CategoryListCreateInput;
// 	siteSetting?: Prisma.SiteSettingCreateInput;
//  };

//  export type OrganizationWithAddress = Organization & {
// 	address: AddressWithCoordinates;
//  };

//  export type OrganizationUpdateType = Organization & {
// 	address: AddressWithCoordinates;
//  };

//  export type OrganizationMetadata = {
// 	metadata?: { productsFetched?: boolean };
//  };

//  export type OrganizationWithOrderDetails = Organization &
// 	Omit<Organization, 'stripeAccountId' | 'createdAt' | 'updatedAt'> & {
// 		address: AddressWithCoordinates;
// 	};

//  export type OrganizationWithShopDetails = Organization &
// 	Omit<Organization, 'stripeAccountId' | 'createdAt' | 'updatedAt'> & {
// 		address: AddressWithCoordinates;
// 		images: ImageOrganization[];
// 		products: ProductWithShopDetails[];
// 		categoryList: CategoryList;
// 		schedule: Schedule[];
// 		vendor: Vendor;
// 		siteSetting: SiteSetting;
// 	};

//  export type OrganizationWithDashboardDetails = Organization & {
// 	products: ProductWithDashboardDetails[];
// 	orders: Order[];
// 	address: AddressWithCoordinates;
// 	memberships: MembershipWithUser[];
// 	images: ImageOrganization[];
// 	categoryList: CategoryList;
// 	categories?: Category[];
// 	siteSetting: SiteSetting;
// 	subscriptionPlan: SubscriptionPlan;
// 	schedule: Schedule[];
// 	subdomain: SubDomain;
// 	vendor: Vendor;
//  };

//  export type UserLocation = {
// 	userLocation: Coordinates;
// 	proximityRadius: number;
//  };

export interface Schedule {
	day: string;
	openAt: number | string;
	closeAt: number | string;
}

export type Invitation = unknown;


const dispensaries: Dispensary[] = [
	{
		id: 'a688d146-6872-4031-a795-b0d7c5e4dc30',
		name: 'Dazed Cannabis',
		phone: '3323332035',
		timeZone: 'America/New_York',
		address: {
			id: 'a688d146-6872-4031-a795-b0d7c5e4dc30',
			coordinateId: 'a688d146-6872-4031-a795-b0d7c5e4dc30',
			city: 'New York',
			state: 'NY',
			country: 'United States',
			street1: '33 Union Square W',
			street2: ' ',
			zipcode: '10003',
			countryCode: 'US',
			coordinates: {
				latitude: 40.73698458282193,
				longitude: -73.99082241547272,
			},
		},
		dialCode: '1',
		stripeAccountId: undefined,
		stripeOnboardingComplete: false,
		termsAccepted: false,
		ecommerceUrl:
			'https://dazed.fun/shop/?pagination=1&sort=NAME_ASC&retailer_id=a688d146-6872-4031-a795-b0d7c5e4dc30&menu_type=RECREATIONAL&collection_type=PICKUP',
		showInMarketPlace: true,
		schedule: [
			{
				day: 'Monday',
				openAt: 800,
				closeAt: 2000,
			},
			{
				day: 'Tuesday',
				openAt: 800,
				closeAt: 2000,
			},
			{
				day: 'Wednesday',
				openAt: 800,
				closeAt: 2000,
			},
			{
				day: 'Thursday',
				openAt: 800,
				closeAt: 2000,
			},
			{
				day: 'Friday',
				openAt: 800,
				closeAt: 2000,
			},
			{
				day: 'Saturday',
				openAt: 800,
				closeAt: 2000,
			},
			{
				day: 'Sunday',
				openAt: 800,
				closeAt: 2000,
			},
		],
		images: [
			{
				location:
					'https://f5d8da031790bc54-image-dispensary.s3.amazonaws.com/dazed/logo-small.png',
				blurhash: 'L4DPD$ju1q,v]Xa|Woo21CWo|}S1',
				alt: 'Dazed Cannabis',
			},
		],
		siteSetting: {
			title: 'Dazed Cannabis',
			showTitle: true,
			description: 'Welcome to Dazed',
			showDescription: true,
			bannerText: 'Shop at Dazed',
			showBanner: true,
			primaryColor: '#F8319D',
			secondaryColor: '#adadad',
			tertiaryColor: '#adadad',
			textColor: '#ffffff',
			backgroundColor: '#000000',
		},
		slug: 'dazed',
		subscriptionPlanId: '',
	},

	{
		id: 'bf346k4u7x2b2hhr6wsofppp',
		name: 'SMACKED Village',
		timeZone: 'America/New_York',
		phone: '9734345112',
		address: {
			id: 'a688d146-6872-4031-a795-b0d7c5e4dc32',
			coordinateId: 'a688d146-6872-4031-a795-b0d7c5e4dc32',
			city: 'New York',
			state: 'NY',
			country: 'United States',
			street1: '144 Bleecker Street',
			street2: ' ',
			zipcode: '10012',
			countryCode: 'US',
			coordinates: {
				latitude: 40.728242028075094,
				longitude: -73.99933475473631,
			},
		},
		dialCode: '1',
		stripeAccountId: undefined,
		stripeOnboardingComplete: false,
		termsAccepted: false,
		ecommerceUrl: 'https://getsmacked.online/menu/',
		showInMarketPlace: true,
		schedule: [
			{
				day: 'Monday',
				openAt: 1100,
				closeAt: 2100,
			},
			{
				day: 'Tuesday',
				openAt: 1100,
				closeAt: 2100,
			},
			{
				day: 'Wednesday',
				openAt: 1100,
				closeAt: 2100,
			},
			{
				day: 'Thursday',
				openAt: 1100,
				closeAt: 2200,
			},
			{
				day: 'Friday',
				openAt: 1000,
				closeAt: 0,
			},
			{
				day: 'Saturday',
				openAt: 1000,
				closeAt: 0,
			},
			{
				day: 'Sunday',
				openAt: 1100,
				closeAt: 1900,
			},
		],
		orders: [
			{
				total: 12399,
				taxFactor: 0.6,
				taxAmount: 1239,
				orderStatus: 'Pending',
				subtotal: 12000,
				customer: {
					id: 'bfhk6k4u7xq030hr6wvgiwao',
					firstName: 'Bob',
					lastName: 'Roberts',
					username: 'BigChiefa22',
					email: 'bmejia220@gmail.com',
					phone: '1232343453',
					emailVerified: false,
					scannedDOB: new Date(),
					is_legal_age: false,
					id_verified: false,
					isSignUpComplete: false,
					dialCode: '1',
					idFrontImage: null,
					idBackImage: null,
					termsAccepted: true,
				},
				driver: {
					driver: {
						email: 'bmejiadeveloper2@gmail.com',
					},
					email: 'bmejiadeveloper2@gmail.com',
					id: 'bf346k4u7x2b2hhr6wvgiwao',
					firstName: 'Bryant',
					lastName: 'Mejia',
					username: 'BigChiefa',
					phone: '1232343456',
					emailVerified: true,
					is_legal_age: null,
					id_verified: true,
					isSignUpComplete: true,
					dialCode: '1',
					idFrontImage: '',
					idBackImage: '',
					termsAccepted: true,
				},
				destinationAddress: {
					street1: '11722 Reisterstown Rd',
					street2: '',
					city: 'Reisterstown',
					state: 'MD',
					zipcode: 21136,
					country: 'United States',
					countryCode: 'US',
					coordinates: {
						radius: 10000,
						latitude: 39.445438,
						longitude: -76.809394,
						createdAt: new Date(),
						updatedAt: new Date(),
					},
				},
				purchase: {
					paymentStatus: 'Pending',
					gateway: 'stripe',
					type: 'card',
					amount: 12399,
					token: '12345',
					createdAt: new Date(),
					updatedAt: new Date(),
				},
				routeId: null,
				isDeliveredOrder: false,
				isCustomerReceivedOrder: false,
				isCompleted: false,
				createdAt: new Date(),
				updatedAt: new Date(),
				deliveryDeadline: new Date(Date.now() + 2 * 60 * 60 * 1000),
				isDriverAssigned: false,
				driverAssignedAt: new Date(),
				isProductPickedUp: false,
				productPickedUpAt: new Date(),
				customerReceivedOrderAt: new Date(),
				completedAt: new Date(),
				deliveredAt: new Date(),
			},
		],
		images: [
			{
				location:
					'https://f5d8da031790bc54-image-dispensary.s3.amazonaws.com/smacked-village/logo-small.png',
				blurhash: 'L4DPD$ju1q,v]Xa|Woo21CWo|}S1',
				alt: 'Smacked Village',
			},
		],
		siteSetting: {
			title: 'SMACKED Village',
			showTitle: true,
			bannerText: 'Shop at Smacked Village',
			showBanner: true,
			description: `We are now open at 144 Bleeker Street, stop by and see us.`,
			showDescription: true,
			primaryColor: '#EE2C44',
			secondaryColor: '#adadad',
			tertiaryColor: '#ffffff',
			textColor: '#689284',
			backgroundColor: '#000000',
		},
		slug: 'smacked-village',
		subscriptionPlanId: '',
	},
	{
		id: 'a688d146-6872-4031-a795-b0d7c5e4dc33',
		name: 'gotham',
		timeZone: 'America/New_York',
		phone: '6462174544',
		address: {
			id: 'a688d146-6872-4031-a795-b0d7c5e4dc33',
			coordinateId: 'a688d146-6872-4031-a795-b0d7c5e4dc33',
			city: 'New York',
			state: 'NY',
			country: 'United States',
			street1: '3 East 3rd Street',
			street2: ' ',
			zipcode: '10003',
			countryCode: 'US',
			coordinates: {
				latitude: 40.72649918483451,
				longitude: -73.99131156150553,
			},
		},
		dialCode: '1',
		stripeAccountId: undefined,
		stripeOnboardingComplete: false,
		termsAccepted: false,
		ecommerceUrl: 'https://www.gotham.nyc/menu',
		showInMarketPlace: true,
		schedule: [
			{
				day: 'Monday',
				openAt: 1000,
				closeAt: 2200,
			},
			{
				day: 'Tuesday',
				openAt: 1000,
				closeAt: 2200,
			},
			{
				day: 'Wednesday',
				openAt: 1000,
				closeAt: 2200,
			},
			{
				day: 'Thursday',
				openAt: 1000,
				closeAt: 2200,
			},
			{
				day: 'Friday',
				openAt: 1000,
				closeAt: 2200,
			},
			{
				day: 'Saturday',
				openAt: 1000,
				closeAt: 2200,
			},
			{
				day: 'Sunday',
				openAt: 1000,
				closeAt: 2200,
			},
		],
		images: [
			{
				location:
					'https://f5d8da031790bc54-image-dispensary.s3.amazonaws.com/gotham/logo-small.png',
				blurhash: 'L4DPD$ju1q,v]Xa|Woo21CWo|}S1',
				alt: 'Gotham',
			},
		],
		siteSetting: {
			title: 'gotham',
			showTitle: true,
			bannerText: 'Shop at gotham',
			showBanner: true,
			description: `A woman-owned cannabis concept space.`,
			showDescription: true,
			primaryColor: '#A3998C',
			secondaryColor: '#2C4B4C',
			tertiaryColor: '#000000',
			textColor: '#000000',
			backgroundColor: '#ffffff',
		},
		slug: 'gotham',
		subscriptionPlanId: '',
	},
	{
		id: 'a688d146-6872-4031-a795-b0d7c5e4dc34',
		name: 'Housing Works',
		timeZone: 'America/New_York',
		phone: '6462174544',
		address: {
			id: 'a688d146-6872-4031-a795-b0d7c5e4dc34',
			coordinateId: 'a688d146-6872-4031-a795-b0d7c5e4dc34',
			city: 'New York',
			state: 'NY',
			country: 'United States',
			street1: '750 Broadway',
			street2: ' ',
			zipcode: '10003',
			countryCode: 'US',
			coordinates: {
				latitude: 40.73104844953167,
				longitude: -73.9923738153411,
			},
		},
		dialCode: '1',
		stripeAccountId: undefined,
		stripeOnboardingComplete: false,
		termsAccepted: false,
		ecommerceUrl: 'https://hwcannabis.co/',
		showInMarketPlace: true,
		schedule: [
			{
				day: 'Monday',
				openAt: 1000,
				closeAt: 2000,
			},
			{
				day: 'Tuesday',
				openAt: 1000,
				closeAt: 2000,
			},
			{
				day: 'Wednesday',
				openAt: 1000,
				closeAt: 2000,
			},
			{
				day: 'Thursday',
				openAt: 1000,
				closeAt: 2100,
			},
			{
				day: 'Friday',
				openAt: 1000,
				closeAt: 2100,
			},
			{
				day: 'Saturday',
				openAt: 1000,
				closeAt: 2100,
			},
			{
				day: 'Sunday',
				openAt: 1100,
				closeAt: 1900,
			},
		],
		images: [
			{
				location:
					'https://f5d8da031790bc54-image-dispensary.s3.amazonaws.com/housing-works/logo-small.png',
				blurhash: 'L4DPD$ju1q,v]Xa|Woo21CWo|}S1',
				alt: 'Housing Works Cannabis Co.',
			},
		],
		siteSetting: {
			title: 'Housing Works',
			showTitle: true,
			bannerText: 'Shop at Housing Works',
			showBanner: true,
			description: `All proceeds from Housing Works Cannabis Co support Housing Works, a NYC nonprofit dedicated to relentless advocacy, lifesaving services, and justice for all.`,
			showDescription: true,
			primaryColor: '#4A5660',
			secondaryColor: '#2C4B4C',
			tertiaryColor: '#000000',
			textColor: '#000000',
			backgroundColor: '#ffffff',
		},
		slug: 'housing-works',
		subscriptionPlanId: '',
	},
	{
		id: 'a688d146-6872-4031-a795-b0d7c5e4dc37',
		name: 'Verdi',
		phone: '6462174544',
		timeZone: 'America/New_York',
		address: {
			id: 'a688d146-6872-4031-a795-b0d7c5e4dc37',
			coordinateId: 'a688d146-6872-4031-a795-b0d7c5e4dc37',
			city: 'New York',
			state: 'NY',
			country: 'United States',
			street1: '158 West 23rd St',
			street2: '',
			zipcode: '10011',
			countryCode: 'US',
			coordinates: {
				latitude: 40.744376372717866,
				longitude: -73.99484942326792,
			},
		},
		dialCode: '1',
		stripeAccountId: undefined,
		stripeOnboardingComplete: false,
		termsAccepted: false,
		ecommerceUrl: 'https://verdicannabis.com/',
		showInMarketPlace: true,
		schedule: [
			{
				day: 'Monday',
				openAt: 1200,
				closeAt: 2200,
			},
			{
				day: 'Tuesday',
				openAt: 1200,
				closeAt: 2200,
			},
			{
				day: 'Wednesday',
				openAt: 1200,
				closeAt: 2200,
			},
			{
				day: 'Thursday',
				openAt: 1200,
				closeAt: 2200,
			},
			{
				day: 'Friday',
				openAt: 1200,
				closeAt: 2200,
			},
			{
				day: 'Saturday',
				openAt: 1200,
				closeAt: 2200,
			},
			{
				day: 'Sunday',
				openAt: 1200,
				closeAt: 2200,
			},
		],
		images: [
			{
				location:
					'https://f5d8da031790bc54-image-dispensary.s3.amazonaws.com/verdi/logo-small.png',
				blurhash: 'L4DPD$ju1q,v]Xa|Woo21CWo|}S1',
				alt: 'Terp Bros',
			},
		],
		siteSetting: {
			title: 'Verdi',
			showTitle: true,
			bannerText:
				'WE PROVIDE THE VERY BEST CANNABIS PRODUCTS TO PEOPLE FROM ALL-WALKS OF LIFE'.toLowerCase(),
			showBanner: true,
			description:
				`NY'S FIRST 100% FAMILY-OWNED, LEGAL CANNABIS SHOP`.toLowerCase(),
			showDescription: true,
			primaryColor: '#111111',
			secondaryColor: '#111111',
			tertiaryColor: '#000000',
			textColor: '#000000',
			backgroundColor: '#ffffff',
		},
		slug: 'verdi',
		subscriptionPlanId: '',
	},
	{
		id: 'a688d146-6872-4031-a795-b0d7c5e4dc31',
		name: 'CONBUD',
		phone: '6464490809',
		timeZone: 'America/New_York',
		address: {
			id: 'a688d146-6872-4031-a795-b0d7c5e4dc31',
			coordinateId: 'a688d146-6872-4031-a795-b0d7c5e4dc31',
			city: 'New York',
			state: 'NY',
			country: 'United States',
			street1: '85 Delancey Street',
			street2: ' ',
			zipcode: '10002',
			countryCode: 'US',
			coordinates: {
				latitude: 40.718895,
				longitude: -73.989599,
			},
		},
		dialCode: '1',
		stripeAccountId: undefined,
		stripeOnboardingComplete: false,
		termsAccepted: false,
		ecommerceUrl: 'https://www.conbud.com/products',
		showInMarketPlace: true,
		schedule: [
			{
				day: 'Monday',
				openAt: 1100,
				closeAt: 2300,
			},
			{
				day: 'Tuesday',
				openAt: 1100,
				closeAt: 2300,
			},
			{
				day: 'Wednesday',
				openAt: 1100,
				closeAt: 2300,
			},
			{
				day: 'Thursday',
				openAt: 1100,
				closeAt: 2300,
			},
			{
				day: 'Friday',
				openAt: 1100,
				closeAt: 0,
			},
			{
				day: 'Saturday',
				openAt: 1100,
				closeAt: 0,
			},
			{
				day: 'Sunday',
				openAt: 1100,
				closeAt: 2200,
			},
		],
		images: [
			{
				location:
					'https://f5d8da031790bc54-image-dispensary.s3.amazonaws.com/conbud/logo-small.png',
				blurhash: 'L4DPD$ju1q,v]Xa|Woo21CWo|}S1',
				alt: 'Conbud',
			},
		],
		siteSetting: {
			title: 'CONBUD',
			showTitle: true,
			bannerText: 'Shop at CONBUD',
			showBanner: true,
			description: `We are the world's first and only dispensary run and operated by formerly incarcerated professionals.`,
			showDescription: true,
			primaryColor: '#000000',
			secondaryColor: '#2C4B4C',
			tertiaryColor: '#000000',
			textColor: '#689284',
			backgroundColor: '#ffffff',
		},
		slug: 'conbud',
		subscriptionPlanId: '',
	},

	{
		id: 'a688d146-6872-4031-a795-b0d7c5e4dc35',
		name: 'The Cannabis Place',
		phone: '6462174544',
		timeZone: 'America/New_York',
		address: {
			id: 'a688d146-6872-4031-a795-b0d7c5e4dc35',
			coordinateId: 'a688d146-6872-4031-a795-b0d7c5e4dc35',
			city: 'Queens',
			state: 'NY',
			country: 'United States',
			street1: '74-03 Metropolitan Ave',
			street2: ' ',
			zipcode: '11379',
			countryCode: 'US',
			coordinates: {
				latitude: 40.71318824966558,
				longitude: -73.87810524583793,
			},
		},
		dialCode: '1',
		stripeAccountId: undefined,
		stripeOnboardingComplete: false,
		termsAccepted: false,
		ecommerceUrl: 'https://thecannabisplace.org/store/',
		showInMarketPlace: true,
		schedule: [
			{
				day: 'Monday',
				openAt: 1200,
				closeAt: 2000,
			},
			{
				day: 'Tuesday',
				openAt: 1200,
				closeAt: 2000,
			},
			{
				day: 'Wednesday',
				openAt: 1200,
				closeAt: 2000,
			},
			{
				day: 'Thursday',
				openAt: 1200,
				closeAt: 2000,
			},
			{
				day: 'Friday',
				openAt: 1200,
				closeAt: 2000,
			},
			{
				day: 'Saturday',
				openAt: 1200,
				closeAt: 2000,
			},
			{
				day: 'Sunday',
				openAt: 1200,
				closeAt: 2000,
			},
		],
		images: [
			{
				location:
					'https://f5d8da031790bc54-image-dispensary.s3.amazonaws.com/cannabis-place/logo-small.png',
				blurhash: 'L4DPD$ju1q,v]Xa|Woo21CWo|}S1',
				alt: 'The Cannabis Place',
			},
		],
		siteSetting: {
			title: 'The Cannabis Place',
			showTitle: true,
			bannerText: 'Shop at The Cannabis Place',
			showBanner: true,
			description: `Our company is led by our Service Disabled Veteran, Minority Owned and justice involved team. `,
			showDescription: true,
			primaryColor: '#111111',
			secondaryColor: '#111111',
			tertiaryColor: '#000000',
			textColor: '#000000',
			backgroundColor: '#ffffff',
		},
		slug: 'cannabis-place',
		subscriptionPlanId: '',
	},
	{
		id: 'a688d146-6872-4031-a795-b0d7c5e4dc36',
		name: 'Terp Bros',
		phone: '6462174544',
		timeZone: 'America/New_York',
		address: {
			id: 'a688d146-6872-4031-a795-b0d7c5e4dc36',
			coordinateId: 'a688d146-6872-4031-a795-b0d7c5e4dc36',
			city: 'Queens',
			state: 'NY',
			country: 'United States',
			street1: '3610 Ditmars Blvd',
			street2: '',
			zipcode: '11105',
			countryCode: 'US',
			coordinates: {
				latitude: 40.85983149588371,
				longitude: -73.91562550869884,
			},
		},
		dialCode: '1',
		stripeAccountId: undefined,
		stripeOnboardingComplete: false,
		termsAccepted: false,
		ecommerceUrl: 'https://www.terpbrosnyc.com/shop/terp-bros/',
		showInMarketPlace: true,
		schedule: [
			{
				day: 'Monday',
				openAt: 1000,
				closeAt: 2200,
			},
			{
				day: 'Tuesday',
				openAt: 1000,
				closeAt: 2200,
			},
			{
				day: 'Wednesday',
				openAt: 1000,
				closeAt: 2200,
			},
			{
				day: 'Thursday',
				openAt: 1000,
				closeAt: 2200,
			},
			{
				day: 'Friday',
				openAt: 1000,
				closeAt: 2300,
			},
			{
				day: 'Saturday',
				openAt: 1000,
				closeAt: 2300,
			},
			{
				day: 'Sunday',
				openAt: 1100,
				closeAt: 2100,
			},
		],
		images: [
			{
				location:
					'https://f5d8da031790bc54-image-dispensary.s3.amazonaws.com/terp-bros/logo-small.png',
				blurhash: 'L4DPD$ju1q,v]Xa|Woo21CWo|}S1',
				alt: 'Terp Bros',
			},
		],
		siteSetting: {
			title: 'Terp Bros',
			showTitle: true,
			bannerText: 'Shop at Terp Bros',
			showBanner: true,
			description: `We invite individuals from all walks of life from the cannabis-curious to seasoned connoisseurs to explore, learn, and discover.`,
			showDescription: true,
			primaryColor: '#111111',
			secondaryColor: '#111111',
			tertiaryColor: '#000000',
			textColor: '#000000',
			backgroundColor: '#ffffff',
		},
		slug: 'terp-bros',
		subscriptionPlanId: '',
	},

	{
		id: 'a688d146-6872-4031-a795-b0d7c5e4dc38',
		name: 'Zen Leaf Elizabeth',
		phone: '6462174544',
		timeZone: 'America/New_York',
		address: {
			id: 'a688d146-6872-4031-a795-b0d7c5e4dc38',
			coordinateId: 'a688d146-6872-4031-a795-b0d7c5e4dc38',
			city: 'Elizabeth',
			state: 'NJ',
			country: 'United States',
			street1: '117 Spring Street',
			street2: '',
			zipcode: '07201',
			countryCode: 'US',
			coordinates: {
				latitude: 40.663164153304855,
				longitude: -74.20563550633847,
			},
		},
		dialCode: '1',
		stripeAccountId: undefined,
		stripeOnboardingComplete: false,
		termsAccepted: false,
		ecommerceUrl:
			'https://zenleafdispensaries.com/locations/elizabeth/recreational-menu/',
		showInMarketPlace: true,
		schedule: [
			{
				day: 'Monday',
				openAt: 1200,
				closeAt: 2100,
			},
			{
				day: 'Tuesday',
				openAt: 1200,
				closeAt: 2100,
			},
			{
				day: 'Wednesday',
				openAt: 1200,
				closeAt: 2100,
			},
			{
				day: 'Thursday',
				openAt: 1200,
				closeAt: 2100,
			},
			{
				day: 'Friday',
				openAt: '0800',
				closeAt: 2200,
			},
			{
				day: 'Saturday',
				openAt: '0800',
				closeAt: 2200,
			},
			{
				day: 'Sunday',
				openAt: 1100,
				closeAt: 1700,
			},
		],
		images: [
			{
				location:
					'https://f5d8da031790bc54-image-dispensary.s3.amazonaws.com/zenleaf/logo-small.png',
				blurhash: 'L4DPD$ju1q,v]Xa|Woo21CWo|}S1',
				alt: 'Zen Leaf',
			},
		],
		siteSetting: {
			title: 'Zen Leaf',
			showTitle: true,
			bannerText: `Shop at Zen Leaf Elizabeth`,
			showBanner: true,
			description: `We’re passionate about cannabis in every way, including cannabis reform`,
			showDescription: true,
			primaryColor: '#111111',
			secondaryColor: '#111111',
			tertiaryColor: '#000000',
			textColor: '#000000',
			backgroundColor: '#ffffff',
		},
		slug: 'zen-leaf',
		subscriptionPlanId: '',
	},
	{
		id: 'a688d146-6872-4031-a795-b0d7c5e4dc39',
		name: 'Exit 31 Exotic',
		slug: 'exit-31-exotic',
		domain: 'exit-31-exotic',
		address: {
			street1: '255 Genesee St',
			street2: '',
			city: 'Utica',
			state: 'NY',
			zipcode: '13501',
			country: 'US',
			countryCode: 'US',
			coordinates: { longitude: -75.234947, latitude: 43.0993 },
		},
		dialCode: '(315) 982-4274',
		phone: '(315) 982-4274',
		schedule: [
			{
				day: '',
				openAt: '10:00am -  9:00pm',
				closeAt: '10:00am -  9:00pm',
			},
		],
		siteSetting: {
			description:
				"Utica's first legal, adult-use dispensary is now open! A new place for you and your buds to call home.",
			title: 'Exit 31 Exotic',
			bannerText: 'Shop at Exit 31 Exotic',
			showTitle: true,
			showBanner: true,
			showDescription: true,
			primaryColor: '#111111',
			secondaryColor: '#111111',
			tertiaryColor: '#000000',
			textColor: '#000000',
			backgroundColor: '#ffffff',
		},
	},
	{
		id: 'a688d146-6872-4031-a795-b0d7c5e4dc40',
		name: 'DOSHA',
		slug: 'dosha',
		address: {
			street1: '76 Main Street',
			street2: '',
			city: 'Oneonta',
			state: 'NY',
			zipcode: '13820',
			country: 'US',
			countryCode: 'US',
			coordinates: { longitude: -75.06365, latitude: 42.45099 },
		},
		dialCode: '1',
		phone: '(607) 267-4488',
		schedule: [
			{
				day: '',
				openAt: '11:00am -  8:00pm',
				closeAt: '11:00am -  8:00pm',
			},
		],
		siteSetting: {
			description:
				'DOSHA is a legal and licensed adult-use cannabis dispensary serving Oneonta, Cooperstown, and the greater Mohawk Region.</p><p>At DOSHA, our focus is on delivering a variety of services customized to cater to your individual requirements. Our team, known for their expertise and approachable demeanor, is devoted to assisting you in navigating through the available choices, ensuring your confidence in your purchase. As an licensed retailer, we take immense pride in presenting premium cannabis products sourced locally from certified growers and processors within the state of New York. This guarantees not only the highest quality but also the safety and reliability of the products you receive.',
			title: 'DOSHA',
			bannerText: 'Shop at DOSHA',
			showTitle: true,
			showBanner: true,
			showDescription: true,
			primaryColor: '#111111',
			secondaryColor: '#111111',
			tertiaryColor: '#000000',
			textColor: '#000000',
			backgroundColor: '#ffffff',
		},
	},
	{
		id: 'a688d146-6872-4031-a795-b0d7c5e4dc41',
		name: 'Sunnyside Medical Cannabis Dispensary – Mohawk Valley',
		slug: 'sunnyside-dispensary-mohawk-valley',
		address: {
			street1: '4776 Commercial Dr',
			street2: '',
			city: 'New Hartford',
			state: 'NY',
			zipcode: '13413',
			country: 'US',
			countryCode: 'US',
			coordinates: {
				longitude: -75.305847,
				latitude: 43.094093,
			},
		},
		dialCode: '1',
		phone: '(518) 219-8051',
		schedule: [
			{
				day: '',
				openAt: '10:00am -  7:00pm',
				closeAt: '10:00am -  7:00pm',
			},
		],
		siteSetting: {
			title: 'Sunnyside Medical Cannabis Dispensary – Mohawk Valley',
			bannerText: 'Shop at Sunnyside',
			description: '',
			showTitle: true,
			showBanner: true,
			showDescription: true,
			primaryColor: '#111111',
			secondaryColor: '#111111',
			tertiaryColor: '#000000',
			textColor: '#000000',
			backgroundColor: '#ffffff',
		},
	},
	{
		id: 'a688d146-6872-4031-a795-b0d7c5e4dc42',
		name: 'Loudpack Exotics',
		slug: 'loudpack-exotics',
		address: {
			street1: '6606 Kinne Rd',
			street2: '',
			city: 'Syracuse',
			state: 'NY',
			zipcode: '13214',
			country: 'US',
			countryCode: 'US',
			coordinates: {
				longitude: -76.06374,
				latitude: 43.042288,
			},
		},
		dialCode: '1',
		phone: '(315) 299-4323',
		schedule: [
			{
				day: '',
				openAt: ' 9:00am -  9:00pm',
				closeAt: ' 9:00am -  9:00pm',
			},
		],
		siteSetting: {
			description:
				'We are your friendly neighborhood cannabis dispensary, licensed by NYS. Elevate your wellness routine today by stopping in to shop our wide selection of exotic strains! Preorder is available for your convenience but there is PLENTY of parking onsite (ADA accessible and compliant). Our guests must be 21 to enter with a valid ID. We accept cash and debit cards only, with an ATM on the premises.',
			title: 'Loudpack Exotics',
			bannerText: 'Shop at Loudpack Exotics',
			showTitle: true,
			showBanner: true,
			showDescription: true,
			primaryColor: '#111111',
			secondaryColor: '#111111',
			tertiaryColor: '#000000',
			textColor: '#000000',
			backgroundColor: '#ffffff',
		},
	},
	{
		id: 'a688d146-6872-4031-a795-b0d7c5e4dc43',
		name: 'Etain Syracuse',
		slug: 'etain-syracuse',
		address: {
			street1: '2140 Erie Boulevard East',
			street2: '',
			city: 'Syracuse',
			state: 'NY',
			zipcode: '13224',
			country: 'US',
			countryCode: 'US',
			coordinates: { longitude: -76.1030007, latitude: 43.0413792 },
		},
		dialCode: '1',
		phone: '(914) 437-7898',
		schedule: [
			{
				day: '',
				openAt: '10:00am -  6:00pm',
				closeAt: '10:00am -  6:00pm',
			},
		],
		siteSetting: {
			title: 'Etain - Syracuse',
			bannerText: 'Shop at Etain Syracuse',
			description:
				"New York's only women-founded medical/adult-use cannabis company since 2015.",
			showTitle: true,
			showBanner: true,
			showDescription: true,
			primaryColor: '#111111',
			secondaryColor: '#111111',
			tertiaryColor: '#000000',
			textColor: '#000000',
			backgroundColor: '#ffffff',
		},
	},
	// {
	// 	name: 'Flynnstoned Cannabis Company',
	// 	slug: 'flynnstoned',
	// 	'domain?': 'flynnstoned',
	// 	street1: '219 Walton Street',
	// 	city: 'Syracuse',
	// 	state: 'New York',
	// 	zipcode: '13202',
	// 	country: 'US',
	// 	countryCode: 'US',
	// 	'coordinates?': '-76.156387',
	// 	'userId?': '43.047818',
	// 	'dialCode?': '(315) 299-9334',
	// 	'phone?': '(315) 299-9334',
	// 	openAt: '10:00am -  9:00pm',
	// 	closeAt: '10:00am -  9:00pm',
	// 	description:
	// 		'<p></p><p>At FlynnStoned Cannabis Company, our mission is to revolutionize the cannabis industry by offering premium quality products, a world-class customer experience, and promoting responsible and inclusive cannabis use.</p>',
	// 	title: 'Flynnstoned Cannabis Company',
	// 	bannerText: '11',
	// 	'images?': 'undefined',
	// },
	// {
	// 	name: 'Verilife - Liverpool',
	// 	slug: 'pharmancannis-liverpool',
	// 	'domain?': 'pharmancannis-liverpool',
	// 	street1: '642 Old Liverpool Road',
	// 	city: 'Liverpool',
	// 	state: 'New York',
	// 	zipcode: '13088',
	// 	country: 'US',
	// 	countryCode: 'US',
	// 	'coordinates?': '-76.193304',
	// 	'userId?': '43.092653',
	// 	'dialCode?': '(315) 666-1185',
	// 	'phone?': '(315) 666-1185',
	// 	openAt: ' 9:00am -  9:00pm',
	// 	closeAt: ' 9:00am -  9:00pm',
	// 	description: '<p></p><p>How can we help you feel better today?</p>',
	// 	title: 'Verilife - Liverpool',
	// 	bannerText: '34',
	// 	'images?': 'undefined',
	// },
	// {
	// 	name: "TJ's Cannabis Co.",
	// 	slug: 'tj-s-cannabis-co',
	// 	'domain?': 'tj-s-cannabis-co',
	// 	street1: '4205 Long Branch Rd Ste 5',
	// 	city: 'Liverpool',
	// 	state: 'New York',
	// 	zipcode: '13090',
	// 	country: 'US',
	// 	countryCode: 'US',
	// 	'coordinates?': '-76.222262',
	// 	'userId?': '43.130438',
	// 	'dialCode?': '(315) 314-6776',
	// 	'phone?': '(315) 314-6776',
	// 	openAt: ' 8:00am - 12:00am',
	// 	closeAt: ' 8:00am - 12:00am',
	// 	description:
	// 		'<p></p><p>We are a <u>Licensed Recreational</u> retailer for the great State of New York. <strong>TJ </strong>has been in the <em>cannabis industry </em>for almost <strong>2</strong> decades, and truly <u>knows</u> this business, and is <em>proud</em> to be serving the area where he was born and raised. </p>',
	// 	title: "TJ's Cannabis Co.",
	// 	bannerText: '19',
	// 	'images?': 'undefined',
	// },
	// {
	// 	name: 'Dryden Dispensary',
	// 	slug: 'dryden-dispensary',
	// 	'domain?': 'dryden-dispensary',
	// 	street1: '2207 Dryden Road',
	// 	city: 'Dryden',
	// 	state: 'New York',
	// 	zipcode: '13053',
	// 	country: 'US',
	// 	countryCode: 'US',
	// 	'coordinates?': '-76.32751',
	// 	'userId?': '42.489202',
	// 	'dialCode?': '(607) 708-4151',
	// 	'phone?': '(607) 708-4151',
	// 	openAt: '10:00am -  8:00pm',
	// 	closeAt: '10:00am -  8:00pm',
	// 	description:
	// 		'<p>Now OPEN!</p><p><br></p><p>At Dryden Dispensary, our mission is to create a professional, warm & welcoming environment, strictly catering to adults 21 & over, for a clientele that ranges from novice consumers to seasoned connoisseurs.</p>',
	// 	title: 'Dryden Dispensary',
	// 	bannerText: '1',
	// 	'images?': 'undefined',
	// },
	// {
	// 	name: "Raven's Joint",
	// 	slug: 'ravensjoint',
	// 	'domain?': 'ravensjoint',
	// 	street1: '4106 NY-31 Suite 903',
	// 	city: 'Clay',
	// 	state: 'New York',
	// 	zipcode: '13041',
	// 	country: 'US',
	// 	countryCode: 'US',
	// 	'coordinates?': '-76.229236',
	// 	'userId?': '43.18466',
	// 	'dialCode?': '(315) 409-4600',
	// 	'phone?': '(315) 409-4600',
	// 	openAt: '10:00am -  7:30pm',
	// 	closeAt: '10:00am -  7:30pm',
	// 	description:
	// 		'<p></p><p>We proudly offers premium Flower, Pre-Rolls, Vapes, Oils, and Drinks, designed to elevate your senses.</p><p>We exclusively stock products approved by New York State, setting us apart from other stores in the Syracuse area.</p><p>Our commitment to the community in Clay and Syracuse stems from our desire to bolster the state’s economy, support local vendors, and ensure the well-being of our customers and their families.</p><p>We are your go-to destination for Cannabis Dispensaries near you in Clay and Syracuse, and we’re standing by to serve you.</p><p>Don’t settle for the ordinary; indulge in the extraordinary with Raven’s Joint – Your premier cannabis store near you.</p><p><br></p>',
	// 	title: "Raven's Joint",
	// 	bannerText: '4',
	// 	'images?': 'undefined',
	// },
	// {
	// 	name: 'Greenery Spot',
	// 	slug: 'greenery-spot',
	// 	'domain?': 'greenery-spot',
	// 	street1: '246 Main Street',
	// 	city: 'Johnson City',
	// 	state: 'New York',
	// 	zipcode: '13790',
	// 	country: 'US',
	// 	countryCode: 'US',
	// 	'coordinates?': '-75.95541',
	// 	'userId?': '42.11501',
	// 	'dialCode?': '(607) 788-1189',
	// 	'phone?': '(607) 788-1189',
	// 	openAt: '10:00am -  9:00pm',
	// 	closeAt: '10:00am -  9:00pm',
	// 	description:
	// 		'<p></p><p>Welcome to Greenery Spot, your premier cannabis dispensary in Johnson City, New York. We are proud to be a trusted provider of top-quality cannabis products to the local community. Our mission is to create a safe and welcoming environment where customers can explore the world of cannabis and discover its benefits.</p>',
	// 	title: 'Greenery Spot',
	// 	bannerText: '29',
	// 	'images?': 'undefined',
	// },
	// {
	// 	name: 'Sacred Bloom',
	// 	slug: 'sacred-bloom',
	// 	'domain?': 'sacred-bloom',
	// 	street1: '1308 Vestal Pkwy E Suite 5',
	// 	city: 'Vestal',
	// 	state: 'New York',
	// 	zipcode: '13850',
	// 	country: 'US',
	// 	countryCode: 'US',
	// 	'coordinates?': '-76.02836',
	// 	'userId?': '42.09147',
	// 	'dialCode?': '(607) 444-3085',
	// 	'phone?': '(607) 444-3085',
	// 	openAt: ' 9:00am -  9:00pm',
	// 	closeAt: ' 9:00am -  9:00pm',
	// 	description:
	// 		'<p></p><p>Beginning of Sacred Bloom</p><p>I decided to start a legal cannabis retail store. Sacred Bloom is a name standing behind an ever-present cannabis role in the spiritual world of mankind. A Bloom that elevates consciousness to higher planes and gives many answers to those who dare to ask the right questions.</p><p><br></p><p>I am part of a social equity program in New York, known as CAURD. This program was designed to help people socially impacted by the illegal drug trade of marijuana in New York. </p><p><br></p><p>Cannabis has always been a big part of my life and now I have a legal cannabis retail store, owned and operated with that being the primary product.</p><p><br></p><p>We carry vapes, carts, flower, disposables, edibles, pipes, concentrates. </p>',
	// 	title: 'Sacred Bloom',
	// 	bannerText: '12',
	// 	'images?': 'undefined',
	// },
	// {
	// 	name: 'Upstate Canna Co',
	// 	slug: 'upstate-canna-co',
	// 	'domain?': 'upstate-canna-co',
	// 	street1: '1613 Union St.',
	// 	city: 'Schenectady',
	// 	state: 'New York',
	// 	zipcode: '12309',
	// 	country: 'US',
	// 	countryCode: 'US',
	// 	'coordinates?': '-73.90501',
	// 	'userId?': '42.80502',
	// 	'dialCode?': '(518) 280-4289',
	// 	'phone?': '(518) 280-4289',
	// 	openAt: ' 9:00am - 11:00pm',
	// 	closeAt: ' 9:00am - 11:00pm',
	// 	description:
	// 		'<p></p><p>Upstate Canna Co is on a mission to provide the highest-quality, locally cultivated, and distributed natural cannabis products from the heart of New York State. Our commitment extends to serving not only the local community and residents but also warmly welcoming incoming tourists seeking the best in cannabis offerings.</p><p>Our values are deeply rooted in the ethical cultivation and processing of cannabis. We believe in products that are not only safe for consumption but also uphold the highest standards of quality. We prioritize the use of ingredients that are not only safe to ingest and digest but also contribute to the overall well-being of our customers.</p><p><br></p>',
	// 	title: 'Upstate Canna Co',
	// 	bannerText: '36',
	// 	'images?': 'undefined',
	// },
	// {
	// 	name: 'Legacy Dispensary',
	// 	slug: 'legacy-dispensers',
	// 	'domain?': 'legacy-dispensers',
	// 	street1: '1839 Central Ave.',
	// 	city: 'Colonie',
	// 	state: 'New York',
	// 	zipcode: '12205',
	// 	country: 'US',
	// 	countryCode: 'US',
	// 	'coordinates?': '-73.848301',
	// 	'userId?': '42.732015',
	// 	'dialCode?': '(518) 387-3310',
	// 	'phone?': '(518) 387-3310',
	// 	openAt: ' 9:00am -  9:00pm',
	// 	closeAt: ' 9:00am -  9:00pm',
	// 	description:
	// 		'<p></p><p><strong>Welcome to Legacy Dispensary, where we strive to provide you with an exceptional experience in a pristine and safe environment.</strong></p><p>We are committed to continually refining our services to ensure you the highest level of satisfaction. We are thrilled to have you join us on this journey, and we can’t wait to show you what else we we are working on.</p><p>Come on in and let us exceed your expectations!</p>',
	// 	title: 'Legacy Dispensary',
	// 	bannerText: '9',
	// 	'images?': 'undefined',
	// },
	// {
	// 	name: 'Brownies Dispensary',
	// 	slug: 'brownies-dispensary-llc',
	// 	'domain?': 'brownies-dispensary-llc',
	// 	street1: '1686 Central ave',
	// 	city: 'Albany',
	// 	state: 'New York',
	// 	zipcode: '12159',
	// 	country: 'US',
	// 	countryCode: 'US',
	// 	'coordinates?': '-73.839088',
	// 	'userId?': '42.722653',
	// 	'dialCode?': '(518) 608-1010',
	// 	'phone?': '(518) 608-1010',
	// 	openAt: ' 9:00am - 10:00pm',
	// 	closeAt: ' 9:00am - 10:00pm',
	// 	description: '',
	// 	title: 'Brownies Dispensary',
	// 	bannerText: '4',
	// 	'images?': 'undefined',
	// },
	// {
	// 	name: 'Verilife - Albany',
	// 	slug: 'verilife-albany',
	// 	'domain?': 'verilife-albany',
	// 	street1: '10 Executive Park Drive',
	// 	city: 'Albany',
	// 	state: 'New York',
	// 	zipcode: '12203',
	// 	country: 'US',
	// 	countryCode: 'US',
	// 	'coordinates?': '-73.83737',
	// 	'userId?': '42.68392',
	// 	'dialCode?': '(888) 493-6066',
	// 	'phone?': '(888) 493-6066',
	// 	openAt: ' 9:00am -  9:00pm',
	// 	closeAt: ' 9:00am -  9:00pm',
	// 	description:
	// 		'<p></p><p>Adult Use sales start 12/29! Sunday 10am-12pm reserved for Medical patients only. </p><p><br></p><p>Our Albany dispensary is east of the I-87 New York Thruway, behind Stuyvesant Plaza and between Crossgates Mall and the University at Albany. We’re also less than 20 miles from many of the surrounding suburbs, including Schenectady, Troy, and Saratoga Springs, Colonie, Mcknownville, Roessleville, and Westmere, and just a few minutes from the Albany International Airport.</p>',
	// 	title: 'Verilife - Albany',
	// 	bannerText: '33',
	// 	'images?': 'undefined',
	// },
	// {
	// 	name: 'Capital District Cannabis & Wellness',
	// 	slug: 'capital-district-cannabis-wellness-inc',
	// 	'domain?': 'capital-district-cannabis-wellness-inc',
	// 	street1: '997 Central Ave.',
	// 	city: 'Albany',
	// 	state: 'New York',
	// 	zipcode: '12205',
	// 	country: 'US',
	// 	countryCode: 'US',
	// 	'coordinates?': '-73.79484',
	// 	'userId?': '42.68489',
	// 	'dialCode?': '(518) 487-4591',
	// 	'phone?': '(518) 487-4591',
	// 	openAt: ' 9:00am -  9:00pm',
	// 	closeAt: ' 9:00am -  9:00pm',
	// 	description:
	// 		'<p></p><p>At Capital District Cannabis & Wellness, we are proud to offer our customers the finest quality products on the market. Our friendly and knowledgeable team is readily available to address any inquiries you may have and assist you in discovering the ideal flower for your requirements. So come on in and explore the world of cannabis with us!  </p><p><br></p>',
	// 	title: 'Capital District Cannabis & Wellness',
	// 	bannerText: '6',
	// 	'images?': 'undefined',
	// },
	// {
	// 	name: 'RISE Dispensary Halfmoon Clifton Park',
	// 	slug: 'rise-halfmoon-clifton-park',
	// 	'domain?': 'rise-halfmoon-clifton-park',
	// 	street1: '1675 Route 9',
	// 	city: 'Halfmoon',
	// 	state: 'New York',
	// 	zipcode: '12065',
	// 	country: 'US',
	// 	countryCode: 'US',
	// 	'coordinates?': '-73.764232',
	// 	'userId?': '42.860649',
	// 	'dialCode?': '(518) 373-4147',
	// 	'phone?': '(518) 373-4147',
	// 	openAt: ' 9:00am -  7:00pm',
	// 	closeAt: ' 9:00am -  7:00pm',
	// 	description: '',
	// 	title: 'RISE Dispensary Halfmoon Clifton Park',
	// 	bannerText: '14',
	// 	'images?': 'undefined',
	// },
	// {
	// 	name: 'Mr. Good Vybz',
	// 	slug: 'mr-good-vybz',
	// 	'domain?': 'mr-good-vybz',
	// 	street1: '25 N. Pearl St.',
	// 	city: 'Albany',
	// 	state: 'New York',
	// 	zipcode: '12207',
	// 	country: 'US',
	// 	countryCode: 'US',
	// 	'coordinates?': '-73.75197',
	// 	'userId?': '42.650375',
	// 	'dialCode?': '(518) 451-9290',
	// 	'phone?': '(518) 451-9290',
	// 	openAt: ' 9:00am - 10:00pm',
	// 	closeAt: ' 9:00am - 10:00pm',
	// 	description:
	// 		'<p></p><p><strong>Minority-Owned and Community-Focused</strong>: We are proud to be a beacon of inclusivity, welcoming a diverse clientele to our community.</p><p><br></p><p><strong>Curated Cannabis Collection</strong>: Our selection is a testament to quality, featuring a wide array of strains, THC levels, and exclusive products.</p><p><br></p><p><strong>Knowledgeable Staff</strong>: Our team is passionate and educated, ready to guide you through our offerings and ensure your needs are met with the utmost care.</p><p><br></p>',
	// 	title: 'Mr. Good Vybz',
	// 	bannerText: '0',
	// 	'images?': 'undefined',
	// },
	// {
	// 	name: 'Royale Flower Cannabis',
	// 	slug: 'royale-flower-cannabis',
	// 	'domain?': 'royale-flower-cannabis',
	// 	street1: '350 Northern Blvd',
	// 	city: 'Albany',
	// 	state: 'New York',
	// 	zipcode: '12204',
	// 	country: 'US',
	// 	countryCode: 'US',
	// 	'coordinates?': '-73.748936',
	// 	'userId?': '42.674985',
	// 	'dialCode?': '(518) 380-3738',
	// 	'phone?': '(518) 380-3738',
	// 	openAt: ' 9:00am -  9:00pm',
	// 	closeAt: ' 9:00am -  9:00pm',
	// 	description:
	// 		'<p></p><p>Located in Albany, NY, Royale Flower stands as the city’s ultimate destination for luxury cannabis and CBD products and accessories. We are not just some place to get your marijuana, but a place to have an high end experience. Our exclusive collections, featuring both renowned and rising brands, are meticulously curated to ensure the highest quality and uniqueness. As Albany’s most distinguished cannabis shop, Royale Flower extends beyond weed offerings to include designer apparel, exquisite jewelry, and sophisticated homewares and gifts, each selected for its exceptional craftsmanship and style. Catering to the discerning tastes of our clientele, Royale Flower embodies exclusivity and sophistication, making it the premier choice for a luxurious cannabis lifestyle.</p>',
	// 	title: 'Royale Flower Cannabis',
	// 	bannerText: '1',
	// 	'images?': 'undefined',
	// },
	// {
	// 	name: 'The Bakery Cannabis Dispensary',
	// 	slug: 'the-bakery-cannabis-dispensary-1',
	// 	'domain?': 'the-bakery-cannabis-dispensary-1',
	// 	street1: '1099 Loudon Rd',
	// 	city: 'Cohoes',
	// 	state: 'New York',
	// 	zipcode: '12047',
	// 	country: 'US',
	// 	countryCode: 'US',
	// 	'coordinates?': '-73.743552',
	// 	'userId?': '42.78387',
	// 	'dialCode?': '(518) 879-1441',
	// 	'phone?': '(518) 879-1441',
	// 	openAt: '11:00am -  8:00pm',
	// 	closeAt: '11:00am -  8:00pm',
	// 	description:
	// 		'<p></p><p>Located in the heart of the Capital Region , we pride ourselves on offering a wide selection of top-quality strains, edibles, concentrates, and accessories to meet the diverse needs of our valued customers.</p>',
	// 	title: 'The Bakery Cannabis Dispensary',
	// 	bannerText: '0',
	// 	'images?': 'undefined',
	// },
	// {
	// 	name: 'Stage One Dispensary',
	// 	slug: 'stage-one-dispensary',
	// 	'domain?': 'stage-one-dispensary',
	// 	street1: '810C Broadway',
	// 	city: 'Rensselaer',
	// 	state: 'New York',
	// 	zipcode: '12144',
	// 	country: 'US',
	// 	countryCode: 'US',
	// 	'coordinates?': '-73.73941',
	// 	'userId?': '42.64641',
	// 	'dialCode?': '(518) 451-9540',
	// 	'phone?': '(518) 451-9540',
	// 	openAt: ' 9:00am -  9:00pm',
	// 	closeAt: ' 9:00am -  9:00pm',
	// 	description:
	// 		'<p></p><p>It all began 30 some years ago, when Nate Innes and Josh Mirsky met in Albany, NY. Both teenagers living with their parents in Center Square, off of Lark Street, Nate, Josh and their crew would meet at Stage One: on the stoops of a brownstone, next to a Bodega, located on the corner of Lark and Jay Streets.</p><p>If you got a page on your pager to your skytel (look it up, it was a thing) that said 42011111, they knew it was meetup time at Stage One.</p><p>Stage One was a jump off point, a place to people watch, a place they would meet to converse, have a laugh, and yes…smoke a jay or two.</p><p>We are staying true to our roots and bringing it back full circle, back to Stage One.</p>',
	// 	title: 'Stage One Dispensary',
	// 	bannerText: '17',
	// 	'images?': 'undefined',
	// },
	// {
	// 	name: 'Northern Lights',
	// 	slug: 'northern-lights',
	// 	'domain?': 'northern-lights',
	// 	street1: '100 Broadway Suite 8',
	// 	city: 'Menands',
	// 	state: 'New York',
	// 	zipcode: '12204',
	// 	country: 'US',
	// 	countryCode: 'US',
	// 	'coordinates?': '-73.734028',
	// 	'userId?': '42.68175',
	// 	'dialCode?': '(518) 472-0278',
	// 	'phone?': '(518) 472-0278',
	// 	openAt: '10:00am -  8:00pm',
	// 	closeAt: '10:00am -  8:00pm',
	// 	description:
	// 		"<p>Northern Lights NY Cannabis Dispensary is located conveniently off Exit 6 on 787 in Menands, NY.</p><p>The site features over 800 cannabis products from NY's top cultivators and processors.</p><p>Come visit the LARGEST CANNABIS SHOWROOM in Albany with over 2,000 square of space to explore all things cannabis. With over 400 parking spaces and only 5 minutes from downtown Albany, Northern Lights is the Capital District's premier Cannabis Dispensary. Now offering delivery to the entire Capital District and beyond.</p>",
	// 	title: 'Northern Lights',
	// 	bannerText: '6',
	// 	'images?': 'undefined',
	// },
	// {
	// 	name: 'Etain - Kingston',
	// 	slug: 'etain-kingston',
	// 	'domain?': 'etain-kingston',
	// 	street1: '445 State Route 28',
	// 	city: 'Kingston',
	// 	state: 'New York',
	// 	zipcode: '12401',
	// 	country: 'US',
	// 	countryCode: 'US',
	// 	'coordinates?': '-74.059118',
	// 	'userId?': '41.961461',
	// 	'dialCode?': '(914) 437-7898',
	// 	'phone?': '(914) 437-7898',
	// 	openAt: '10:00am -  6:00pm',
	// 	closeAt: '10:00am -  6:00pm',
	// 	description:
	// 		"<p>New York's only women-founded medical/adult-use cannabis company since 2015.</p>",
	// 	title: 'Etain - Kingston',
	// 	bannerText: '11',
	// 	'images?': 'undefined',
	// },
	// {
	// 	name: 'Columbia Care - Scranton',
	// 	slug: 'columbia-care-pennsylvania-scranton',
	// 	'domain?': 'columbia-care-pennsylvania-scranton',
	// 	street1: '1790 N Keyser Ave',
	// 	city: 'Scranton',
	// 	state: 'Pennsylvania',
	// 	zipcode: '18508',
	// 	country: 'US',
	// 	countryCode: 'US',
	// 	'coordinates?': '-75.667889',
	// 	'userId?': '41.443365',
	// 	'dialCode?': '(570) 309-6098',
	// 	'phone?': '(570) 309-6098',
	// 	openAt: '10:00am -  6:00pm',
	// 	closeAt: '10:00am -  6:00pm',
	// 	description: '',
	// 	title: 'Columbia Care - Scranton',
	// 	bannerText: '24',
	// 	'images?': 'undefined',
	// },
	// {
	// 	name: 'Trulieve - Scranton',
	// 	slug: 'trulieve-scranton',
	// 	'domain?': 'trulieve-scranton',
	// 	street1: '340 S Washington Avenue',
	// 	city: 'Scranton',
	// 	state: 'Pennsylvania',
	// 	zipcode: '18505',
	// 	country: 'US',
	// 	countryCode: 'US',
	// 	'coordinates?': '-75.668263',
	// 	'userId?': '41.40473',
	// 	'dialCode?': '(570) 217-8885',
	// 	'phone?': '(570) 217-8885',
	// 	openAt: ' 9:00am -  8:00pm',
	// 	closeAt: ' 9:00am -  8:00pm',
	// 	description:
	// 		'<p></p><p>Notice: All visitors must wear a mask or face covering in our dispensaries unless they have a medical condition that prevents them from doing so.</p><p><br></p><p>Harvest HOC is now Trulieve. Our Scranton dispensary offers a personalized experience to meet your cannabis needs. Whatever strain or format you prefer, from flowers to tinctures to edibles and everything in between. Trulieve has the right cannabis for you.</p>',
	// 	title: 'Trulieve - Scranton',
	// 	bannerText: '7',
	// 	'images?': 'undefined',
	// },
	// {
	// 	name: 'The Botanist - Middletown',
	// 	slug: 'the-botanist-middletown',
	// 	'domain?': 'the-botanist-middletown',
	// 	street1: '247 Dunning Rd',
	// 	city: 'Middletown',
	// 	state: 'New York',
	// 	zipcode: '10940',
	// 	country: 'US',
	// 	countryCode: 'US',
	// 	'coordinates?': '-74.383517',
	// 	'userId?': '41.454286',
	// 	'dialCode?': '(845) 243-2940',
	// 	'phone?': '(845) 243-2940',
	// 	openAt: ' 9:00am -  7:00pm',
	// 	closeAt: ' 9:00am -  7:00pm',
	// 	description:
	// 		'<p></p><p>Based in Orange County, NY, The Botanist of Middletown is a unique medical cannabis dispensary rooted in education, community, and experience. Our dispensaries offer the best capsules, vaporizers, cartridges, tinctures, and more. </p>',
	// 	title: 'The Botanist - Middletown',
	// 	bannerText: '11',
	// 	'images?': 'undefined',
	// },
	// {
	// 	name: 'Ethos Wilkes-Barre',
	// 	slug: 'ethos-wilkes-barre',
	// 	'domain?': 'ethos-wilkes-barre',
	// 	street1: '326 Bear Creek Commons',
	// 	city: 'Wilkes-Barre',
	// 	state: 'Pennsylvania',
	// 	zipcode: '18702',
	// 	country: 'US',
	// 	countryCode: 'US',
	// 	'coordinates?': '-75.830503',
	// 	'userId?': '41.2482655',
	// 	'dialCode?': '(484) 660-2035',
	// 	'phone?': '(484) 660-2035',
	// 	openAt: '10:00am -  8:00pm',
	// 	closeAt: '10:00am -  8:00pm',
	// 	description: '',
	// 	title: 'Ethos Wilkes-Barre',
	// 	bannerText: '19',
	// 	'images?': 'undefined',
	// },
	// {
	// 	name: 'Columbia Care - Wilkes-Barre',
	// 	slug: 'columbia-care-pennsylvania-wilkes-barre',
	// 	'domain?': 'columbia-care-pennsylvania-wilkes-barre',
	// 	street1: '765 Kidder St',
	// 	city: 'Wilkes-Barre',
	// 	state: 'Pennsylvania',
	// 	zipcode: '18702',
	// 	country: 'US',
	// 	countryCode: 'US',
	// 	'coordinates?': '-75.843566',
	// 	'userId?': '41.249944',
	// 	'dialCode?': '(570) 362-7020',
	// 	'phone?': '(570) 362-7020',
	// 	openAt: '10:00am -  6:00pm',
	// 	closeAt: '10:00am -  6:00pm',
	// 	description: '',
	// 	title: 'Columbia Care - Wilkes-Barre',
	// 	bannerText: '9',
	// 	'images?': 'undefined',
	// },
	// {
	// 	name: 'Black Market Cannabis Dispensary',
	// 	slug: 'black-market-canna-co-llc',
	// 	'domain?': 'black-market-canna-co-llc',
	// 	street1: '89 Main Street',
	// 	city: 'Poughkeepsie',
	// 	state: 'New York',
	// 	zipcode: '12601',
	// 	country: 'US',
	// 	countryCode: 'US',
	// 	'coordinates?': '-73.935948',
	// 	'userId?': '41.705903',
	// 	'dialCode?': '(845) 204-6224',
	// 	'phone?': '(845) 204-6224',
	// 	openAt: ' 8:00am - 11:45pm',
	// 	closeAt: ' 8:00am - 11:45pm',
	// 	description: '',
	// 	title: 'Black Market Cannabis Dispensary',
	// 	bannerText: '2',
	// 	'images?': 'undefined',
	// },
];

export { dispensaries };
