import { NextSeo, type NextSeoProps } from 'next-seo';
import app from './app';

const SEOMetaTags = ({
	title,
	description,
	additionalMetaTags = [],
	additionalLinkTags = [],
	additionalKeywords = [],
	openGraph = {},
	twitter = {},
	...props
}: NextSeoProps & { additionalKeywords?: string[] }) => {
	return (
		<NextSeo
			title={title || app.name}
			description={description || app.description}
			additionalMetaTags={[
				{
					name: 'viewport',
					content: 'width=device-width, initial-scale=1.0',
				},
				{
					name: 'keywords',
					content: [
						'weed',
						'cannabis',
						'delivery',
						'weed delivery service',
						'bud delivery service',
						'cannabis events',
						'cannabis events near me',
						'cannabis friendly events',
						'weed friendly events',
						'what to do tonight near me',
						'things to do near me',
						'fun things to do near me',
						'attractions near me',
						'activities near me',
						'fun places near me',
						'stuff to do near me',
						'things to do today near me',
						'weed events',
						'places to go near me',
						'places to visit near me',
						'things to do tonight near me',
						'activities for adults near me',
						'events for adults near me',
						'adult events',
						'adult events near me',
						'events happening near me',
						'event near me',
						'events near me',
						'free events near me',
						'free events near me today',
						'free events near me this week',
						'festivals going on near me this weekend',
						'festivals events near me',
						'festivals and events near me this weekend',
						'events on friday',
						'events on saturday',
						'420 events',
						'420 events near me',
						'420 events near me today',
						'420 events happening today',
						'marijuana events',
						'marijuana events near me',
						'cannabis events',
						'cannabis events near me',
						'events near me today',
						'events happening today',
						'happening today',
						'whats happening today',
						'events near me this weekend',
						'what going on this weekend near me',
						'things to do in this area',
						'legal weed',
						'legal cannabis',
						'buy weed online',
						'weed show near me',
						'cannabis delivery',
						'cannabis delivery service',
						'cannabis delivery near me',
						'cannabis delivery new york',
						'cannabis delivery long island',
						'long island weed delivery',
						'long island cannibas delivery',
						'long island cannabis delivery',
						'long island pot delivery',
						'weed delivery',
						'weed apps delivery',
						'weed delivery near me',
						'weed delivery new york',
						'apps that deliver weed',
						'edibles delivery app',
						'apps for buying weed',
						'pot delivery app',
						'good weed app',
						'best weed app',
						'app to buy weed',
						'weed on demand',
						'cannabis delivery app',
						'marijuana app',
						'thc delivery',
						'thc delivery app',
						'marijuana delivery',
						'marijuana delivery app',
						'delta 8 delivery',
						'delta 8 delivery near me',
						'delta 8 delivery new york',
						'delta 8 delivery same day',
						'same day delivery',
						'delta 8 near me',
						'order delta 8 delivery',
						'cbd delivery',
						'cbd delivery near me',
						'dispensary delivery',
						'dispensary delivery near me',
						'marijuana delivery near me',
						'dispensary that deliver near me',
						'dispensary that delivery',
						'closest dispensary',
						'closest dispensary to me',
						'deliver that dispensary',
						'deliver dope',
						'deliver weed',
						'pot delivery',
						'pot delivery near me',
						'pot delivery new york',
						'cart delivery',
						'bud deliver',
						'buds deliver',
						'weed delivery nesr me',
						'weed delivery that take debit card',
						'do any dispensaries deliver near me',
						'online dispensary',
						...additionalKeywords,
					].join(', '),
				},
				{
					name: 'msapplication-TileColor',
					content: '#000000',
				},
				{
					name: 'theme-color',
					content: '#000',
				},
				{
					property: 'charSet',
					content: 'utf-8',
				},
				...additionalMetaTags,
			]}
			openGraph={{
				...app.opengraph,
				...openGraph,
				images: [...(openGraph.images || []), ...app.opengraph.images],
			}}
			twitter={{
				cardType: 'summary_large_image',
				site: '@gras_cannabis',
				handle: '@gras_cannabis',
				...twitter,
			}}
			additionalLinkTags={[
				{
					rel: 'shortcut icon',
					href: '/favicon.ico',
				},
				{
					rel: 'apple-touch-icon',
					sizes: '57x57',
					href: '/favicon.ico',
				},
				{
					rel: 'apple-touch-icon',
					sizes: '60x60',
					href: '/favicon.ico',
				},
				{
					rel: 'apple-touch-icon',
					sizes: '72x72',
					href: '/favicon.ico',
				},
				{
					rel: 'apple-touch-icon',
					sizes: '76x76',
					href: '/favicon.ico',
				},
				{
					rel: 'apple-touch-icon',
					sizes: '114x114',
					href: '/favicon.ico',
				},
				{
					rel: 'apple-touch-icon',
					sizes: '120x120',
					href: '/favicon.ico',
				},
				{
					rel: 'apple-touch-icon',
					sizes: '144x144',
					href: '/favicon.ico',
				},
				{
					rel: 'apple-touch-icon',
					sizes: '152x152',
					href: '/favicon.ico',
				},
				{
					rel: 'apple-touch-icon',
					sizes: '180x180',
					href: '/favicon.ico',
				},
				{
					rel: 'icon',
					sizes: '16x16',
					href: '/favicon.ico',
				},
				{
					rel: 'icon',
					sizes: '32x32',
					href: '/favicon.ico',
				},
				{
					rel: 'icon',
					sizes: '96x96',
					href: '/favicon.ico',
				},
				{
					rel: 'icon',
					sizes: '192x192',
					href: '/favicon.ico',
				},
				{
					rel: 'icon',
					href: 'https://www.test.ie/favicon.ico',
				},
				{
					rel: 'apple-touch-icon',
					href: 'https://www.test.ie/touch-icon-ipad.jpg',
					sizes: '76x76',
				},
				// {
				// 	rel: 'manifest',
				// 	href: '/manifest.json',
				// },
				// {
				// 	rel: 'preload',
				// 	href: 'https://www.test.ie/font/sample-font.woff2',
				// 	as: 'font',
				// 	type: 'font/woff2',
				// 	crossOrigin: 'anonymous',
				// },
				...additionalLinkTags,
			]}
			{...props}
		/>
	);
};
export default SEOMetaTags;
