apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: linkerd-identity
  namespace: linkerd
spec:
  secretName: linkerd-identity
  duration: 48h
  renewBefore: 25h
  issuerRef:
    name: linkerd-identity
    kind: Issuer
  commonName: identity.cluster.local
  dnsNames:
  - identity.cluster.local
  isCA: true
  privateKey:
    algorithm: ECDSA
  usages:
  - cert sign
  - crl sign
  - server auth
  - client auth