const cannabis = [
	'weed',
	'cannabis',
	'legal weed',
	'legal cannabis',
	'buy weed online',
	'weed show near me',
];
const delivery = [
	'delivery',
	'weed delivery service',
	'bud delivery service',
	'cannabis delivery',
	'cannabis delivery service',
	'cannabis delivery near me',
	'cannabis delivery new york',
	'cannabis delivery long island',
	'long island weed delivery',
	'long island cannibas delivery',
	'long island cannabis delivery',
	'long island pot delivery',
	'weed delivery',
	'weed apps delivery',
	'weed delivery near me',
	'weed delivery new york',
	'apps that deliver weed',
	'edibles delivery app',
	'apps for buying weed',
	'pot delivery app',
	'good weed app',
	'best weed app',
	'app to buy weed',
	'weed on demand',
	'cannabis delivery app',
	'marijuana app',
	'thc delivery',
	'thc delivery app',
	'marijuana delivery',
	'marijuana delivery app',
	'delta 8 delivery',
	'delta 8 delivery near me',
	'delta 8 delivery new york',
	'delta 8 delivery same day',
	'same day delivery',
	'delta 8 near me',
	'order delta 8 delivery',
	'cbd delivery',
	'cbd delivery near me',
	'dispensary delivery',
	'dispensary delivery near me',
	'marijuana delivery near me',
	'dispensary that deliver near me',
	'dispensary that delivery',
	'closest dispensary',
	'closest dispensary to me',
	'deliver that dispensary',
	'deliver dope',
	'deliver weed',
	'pot delivery',
	'pot delivery near me',
	'pot delivery new york',
	'cart delivery',
	'bud deliver',
	'buds deliver',
	'weed delivery nesr me',
	'weed delivery that take debit card',
	'do any dispensaries deliver near me',
	'online dispensary',
];

const events = [
	'current events new york',
	'msg new york events',
	'new york events today',
	'new york city events today',
	'discovery green events',
	'events new york',
	'weed show',
	'cannabis events',
	'cannabis events near me',
	'cannabis friendly events',
	'weed friendly events',
	'what to do tonight near me',
	'things to do near me',
	'fun things to do near me',
	'attractions near me',
	'activities near me',
	'fun places near me',
	'stuff to do near me',
	'things to do today near me',
	'weed events',
	'places to go near me',
	'places to visit near me',
	'things to do tonight near me',
	'activities for adults near me',
	'events for adults near me',
	'adult events',
	'adult events near me',
	'events happening near me',
	'event near me',
	'events near me',
	'free events near me',
	'free events near me today',
	'free events near me this week',
	'festivals going on near me this weekend',
	'festivals events near me',
	'festivals and events near me this weekend',
	'events on friday',
	'events on saturday',
	'420 events',
	'420 events near me',
	'420 events near me today',
	'420 events happening today',
	'marijuana events',
	'marijuana events near me',
	'cannabis events',
	'cannabis events near me',
	'events near me today',
	'events happening today',
	'happening today',
	'whats happening today',
	'events near me this weekend',
	'what going on this weekend near me',
	'things to do in this area',
];
const business = [
	'cannabis business help',
	'cannabis business growth',
	'cannabis business success',
	'cannabis retail success',
	'retail success',
	'retail services',
	'cannabis dispensary help',
	'cannabis dispensary sales',
	'cannabis dispensary growth',
	'dispensary growth',
	'delivery growth',
	'cannabis delivery software',
	'cannabis delivery',
	'cannabis home delivery',
	'weed home delivery',
	'bud home delivery',
	'bud delivery to home',
	'home delivery',
	'cannabis business',
	'cannabis business services',
	'cannabis delivery service',
	'weed delivery software',
	'weed delivery business',
	'weed business',
	'dispensary software',
	'weed delivery service',
	'weed delivery help',
	'cannabis delivery help',
	'bud delivery help',
	'help my dispensary',
	'help my cannabis business',
	'dispensary success',
	'merchant services for cannabis businesses',
	'business services for cannabis',
	'cannabis business compliance services',
	'cannabis businesses and services',
	'cannabis business solutions',
	'cannabis delivery business plan',
	'cannabis consulting',
	'cannabis business consulting',
	'cannabis business marketing',
	'cannabis industry business services',
	'cannabis text message marketing',
	'cannabis text message',
	'cannabis sms',
	'dispensary text message',
	'send messages from dispensary',
	'message dispensary customers',
	'weed text',
	'cannabis messaging',
	'cannabis business messag',
	'cannabis business marketing',
	'cannabis business consulting',
	'cannabis marketing solution',
	'cannabis text message marketing',
	'cannabis text message',
	'cannabis sms',
	'dispensary text message',
	'send messages from dispensary',
	'message dispensary customers',
	'weed text',
	'cannabis messaging',
	'cannabis business messag',
	'cannabis business marketing',
	'cannabis business consulting',
	'cannabis marketing solution',
];

export const messaging = [
	'cannabis messaging',
	'cannabis business messag',
	'cannabis text message marketing',
	'cannabis text message',
	'cannabis sms',
	'dispensary text message',
	'send messages from dispensary',
	'message dispensary customers',
	'weed text',
	'cannabis messaging',
	'cannabis business messag',
	'cannabis business marketing',
	'cannabis business consulting',
	'cannabis marketing solution',
	'cannabis text message marketing',
	'cannabis text message',
	'cannabis sms',
	'dispensary text message',
	'send messages from dispensary',
	'message dispensary customers',
	'weed text',
	'cannabis messaging',
	'cannabis business messag',
	'cannabis business marketing',
	'cannabis business consulting',
	'cannabis marketing solution',
];

export default {
	cannabis,
	delivery,
	events,
	business,
	messaging,
};
