---
# adopt these good caching practices: https://docs.gitlab.com/ee/ci/caching/#good-caching-practices
# and these! https://medium.com/disdj/speed-up-npm-yarn-install-in-gitlab-1434437f9857
# Cache
cache:
  key:
    files:
      - yarn.lock
  paths:
    - '.yarn/cache/'
    - 'node_modules/'
    - '**/node_modules/'
  policy: pull

.build_cache:
  stage: cache
  image: node:16
  cache:
    key:
      files:
        - yarn.lock
    paths:
      - '.yarn/cache/'
      - 'node_modules/'
      - '**/node_modules/'
    policy: push
  script: |
    echo -e "\033[0;34m## Building dependencies cache.. ##\033[0m"
    yarn --immutable
  only:
    changes:
      - yarn.lock
  retry:
    max: 2
    when:
      - runner_system_failure
      - stuck_or_timeout_failure

build-cache:
  extends:
    - .build_cache
  only:
    refs:
      - production
      - merge_requests
