---
# Deploy
.module_deploy:
  stage: deploy
  cache: []
  image:
    name: bitnami/kubectl:latest
    entrypoint: ['']
  variables:
    MODULE: ''
    BUILD_CONTEXT: ''
    ROOTDIR: '.'
  script: |
    kubectl config get-contexts
    kubectl config use-context gras1/cannabis-platform-monorepo:gras-cluster

    BUILD_CONTEXT="$(echo "${MODULE}" | sed "s|.*/||")"

    kubectl apply -f "${ROOTDIR}/k8s/service.${BUILD_CONTEXT}.yaml"
    kubectl get pods